### ISSUE TITLE
[台北/南港][90K~] Bitmark Inc. DevOps Engineer

### ISSUE THREAD

**Issue by JasonLiuBitmark** [golangtw/jobs#100]
# DevOps Engineer

REPORTS TO: ENGINEERING MANAGER
DATE: NOV 2020 
LOCATION: TAIPEI, TAIWAN

Bitmark Inc. – a venture backed software company – is looking for candidates to join our team and accelerate development of our blockchain and related services. You'll get to work in an environment that deeply values design and engineering, alongside a talented team with industry-proven open source (we are ex-Openmoko people) and design experience.

About the company: Bitmark Inc. is a blockchain startup defining property for the digital environment by enabling issuance of property titles for digital assets. As the facilitating network for ownership and stewardship of personal digital ecologies, Bitmark embraces creators and digital environmentalists vying for a healthy internet and Internet of Things.

## Essential job functions

- Manage the deployment of the Bitmark blockchain and many related services to both staging and production environments
- Implement and maintain CI/CD pipelines
- Maintain the Kubernetes cluster
- Monitor resource usage and costs, and optimize the cost efficiency
- Setup and maintain network and security monitoring

## Profiles that are important to us

- Strong English communication skills
- Strong system administration and networking skills
- Knowledge of OS installation, configuration, and maintenance (we use Ubuntu and FreeBSD)
- Knowledge of cloud service providers (DigitalOcean and AWS)
- Knowledge of container systems (Kubernetes, FreeBSD Jails)
- Knowledge of automated integration tools (TravisCI integration with Github)
- Knowledge of automated deployment tools (Ansible)
- Knowledge of database backup and monitoring (PostgreSQL, LevelDB, Redis, MongoDB, …)
- Knowledge of network monitoring and performance
- Solid security and network hardening fundamentals
- You are creative and analytical, and like to be appreciated for both
- You are passionate about contributing to open-source codebases

## Benefits

- Flexible startup company culture with diverse, international team
- Competitive salary
- Stock options
- Childcare benefits

**Comment by appleboy** [comment]
請問這是需要寫 Golang 的工作嗎？

**Comment by JasonLiuBitmark** [comment]
不好意思，我跟主管確認過之後，這個要用Golang的成分不高。我會刪除此issue。
