### ISSUE TITLE
[台北][月薪70K-120K][樂欣國際]  PhotoGrid - Backend Engineer

### ISSUE THREAD

**Issue by myyang** [golangtw/jobs#108]
## 團隊簡介

[Photogrid](https://www.photogrid.app/) 是 IG 網美必備的相片編輯軟體，臉部貼圖、美顏自拍、梗圖、幻燈片、長條圖、Pattern 動態壁紙全都有！一個 APP，就滿足所有照片和影片拼貼及編輯的需求，再也不用下載一堆 APP 還怕空間不夠！你，就是 P 圖大師

## 工作地點

台北/中正區

## 工作內容

* 參與整個 App 開發、營運生命週期，與 PM 交流技術可行性和定義需求
* 與前端和 App 工程師合作開發新功能
* 維護現有系統，如：debug 和優化
* 提供其他團隊成員培訓和幫助
* 如有需要時可帶領團隊或專案

## 能力需求

* 了解Web開發週期、技術和工具。
* 熟悉服務器端程式語言，如：Go，Python，PHP
* 熟悉雲端服務，如：AWS
* 熟悉 SQL 或 NoSQL 資料庫，如：MySQL 和 DynamoDB
* 有解決問題的能力

## 加分能力

* 熟悉前端語言，例如：HTML，JavaScript 和 CSS
* 具有CI / CD工具的經驗，例如：Gitlab 和 Jenkins
* 具有系統監視的經驗，例如：ELK

## 薪資範圍

70K - 120K TWD / 月 * 13 個月 + bonus

## 工時/特休

0930 - 1830 (彈性工時，可 shift)

## 聯絡方式

直接覆歷至 garfield.yang@ijoyful.com

謝謝

**Comment by appleboy** [comment]
幫加上 Label 了
