### ISSUE TITLE
[台北/信義][月薪8萬以上][M800 台灣資信] Sr. Backend Engineer - golang

### ISSUE THREAD

**Issue by eaglerayp** [golangtw/jobs#109]
## 團隊簡介

公司名稱:
M800 Taiwan Limited 台灣資信有限公司
統編: 50766514
Cinnox platform 網址: https://www.cinnox.com/
104 職缺頁面: https://www.104.com.tw/job/653o3?jobsource=company_job

香港電信商 M800 於 2007 年由一群電信先驅創立而成，旨在徹底改變全球通信，致力於幫助全球各地的企業應對最棘手的通信挑戰。
台北研發團隊正致力於 cinnox 企業解決方案的產品實作。

主要服務項目:
[cinnox]
開創性融合數據平台 cinnox 為企業提供內部協同通訊及客戶服務體驗的全面通訊解決方案。
cinnox 以創新的多維融合模型為設計核心，能夠高效整合多個通訊管道，包括 PSTN 及 VoIP 電話，網站，應用程序和社交媒體。

## 工作地點

台北市信義區信義路五段7號45樓C區 (101 辦公大樓 45F C區)

## 團隊技術

* 使用 gitlab 進行版本控制及審核
* Devops 使用 Jenkins 建立 pipeline 進行自動化測試與部署， terraform 處理 AWS 自動化部屬。
* 使用 Go 語言開發商業邏輯，後端系統目前採行 micro services 架構
* 基礎建設: Kubernetes Cluster，並有多個環境供測試，開發及壓力測試。
* 生產環境建於雲端: AWS 和 Aliyun，滿足全球化客戶需求
* 使用 MQTT， Restful API ， websocket 與前端互動
* 資料庫使用 MongoDB, Redis, MariaDB, VaultDB
* Message Queue/pub-sub service: Kafka, [nats.io](https://nats.io/)
* 使用 Grafana + Prometheus + Alert Manager 監控服務狀態

## 職涯提升與組織內升遷制度

* 每月固定與主管 1-1 確認表現/成長/感受，對齊工作短期與長期目標和職涯規劃
* 依績效，每半年即有一次提名升遷的機會
* 升遷會伴隨明確有感加薪和績效標準改變

## 工作內容

* 實現產品商務需求， 設計和開發商業邏輯，提供 API 與前端（Web/iOS/Android）互動。
* 維護現有的後端功能包括但不限於：即時通訊、SMS、email、MQTT、cloud storage (AWS/阿里雲)、Mobile Push、外部系統整合、任務分派系統、計價、資料分析和搜尋引擎。
* 處理效能問題和改善 legacy code。
* 研究相關領域新知，保持知識分享團隊文化。
* 以 project team (scrum) 形式與前端開發人員，UI/X 設計，QA 以及 PM/PO 協作。系統維護方面與 OP/IT/CICD/SRE 等團隊共同促進系統穩定度。 
* 協助並輔導 junior team member 有關開發能力的提升，協作處事的方法。

### First month Expectation

* 了解團隊運作現狀，團隊目標，摸索目前產品功能。
* 搭建自己的工作環境，掌握當前的部屬環境與 Release Process。
* 藉由 code review，了解團隊的 coding pattern 和設計原則。
* 掌握目前使用的相關技術與使用方式 (e.g. Kubernetes, Kafka, NATS, Redis, MongoDB, etc.)
* 在 mentor 的協助下，完成初期暖身的 Tasks。
* 與主管確認試用期(前三個月)通過標準。

### First three months Expectation

* 進入 Feature 專案開發團隊，在團隊陪同下交付專案。整個專案過程會參與需求確認、討論、系統分析、實作開發、測試、部署。
* 掌握分配的系統元件功能與設計細節，當前資料處理的設計目的 (e.g. DB Schema, Data flow, etc.)
* 與主管定期確認狀況，確保熟悉團隊方向，滿足試用期通過標準

### First six months  Expectation

* 持續 refactor 改善 code base 的 quality/ performance/ process 。
* 能扮演單一專案的 owner 角色，統整團隊專案成員，處理資源調配與風險管理等工作，兼任對內對外的溝通窗口，增進跨團隊擁有感。
* 從分析系統瓶頸，提出可被實踐的改善/解決方案 (e.g. RCA → 測試報告 → 解決方案 → 排入 roadmap)。
* 持續參與團隊流程和活動回饋 (team KT, retro ...)，促使團隊持續進步。
* 了解產品下一階段目標，事前規劃協助推動產品迭代。
* 與 Team Lead 討論下一階段的職涯規劃。

## 能力需求/標準

* 精通至少一種主流後端程式語言 (C++, python, php, java, golang, ruby) (精通的定義是包含基本 CRUD API 設計，schema design，熟悉 concurrent & data race 處理)
* 熟悉至少一種資料庫 (SQL/NoSQL) 操作與 schema design
* 基本版本控管概念 (Git)
* 順暢的團隊協作能力
* 能獨立完成被交付專案，包含釐清不確定性，系統分析與時程規劃，與前端和PM協調開發順序。
* 能處理負責範圍的 end-to-end/ production/ performance issue。

## 加分能力

* 精通 Golang 開發。 (部分列出我們使用的 go tech-stack & library: gin, go-mongo-driver, logrus, redigo, confluent-kafka-go, worker pool, limited concurrency, singleflight)
* mentoring/coaching 經驗
* 了解 Linux 底層，網路/資安理論， Docker 及 Kubernetes 相關技術
* 大量的資料庫操作和效能分析與改善經驗
* 開發同時具有 Devops mindset，考慮系統上線後續 debug, monitor, alert 等面向。
* 艱深的系統問題發現與處理，對於特定領域主題研究有興趣及實際經歷。

## 薪資範圍

* 最低月薪80k以上，依能力面議

## 工時/特休

* 每日工作時間: 9:00 AM ~ 6:00 PM  中午休息(12:00~1:00)
* 加班費制度： 呈報加班費，計算比照勞基法，不常態性加班
* 試用期滿三天，第一年即享有 10 天年假

## 聯絡方式

Mike Duh
E-mail: mikeduh@m800.com
標題請註明 應徵 M800 Senior Backend Developer
履歷夾帶於 email 附件

**Comment by appleboy** [comment]
已上 Tag

**Comment by eaglerayp** [comment]
@appleboy   內容標題更新，請幫忙更新tag

**Comment by appleboy** [comment]
@eaglerayp  已更新

**Comment by eaglerayp** [comment]
no position now.
