### ISSUE TITLE
[台北/信義][年薪 1200K ~ 1800K][OneDegree] Sr. Backend Engineer

### ISSUE THREAD

**Issue by Hwrdy** [golangtw/jobs#110]
## 團隊簡介
大家好！
我們是 OneDegree 我們近期正在尋找 2 位 後端工程師夥伴，如果對職位有興趣，歡迎隨時來信與我聊聊細節～

關於 OneDegree

OneDegree 成立於2016年，致力通過數位化保險平台來改變傳統保險市場，於香港經營虛擬保險業務的科技保險公司，於香港市場推出首個純醫療寵物保險；另一方面也致力為保險公司和保險服務商提供數位解決方案，以科技的力量為業內領導者打造全新保險體驗。

## 工作地點
台北市信義區信基大樓

## 工作內容
- Design, build and maintain backend services for B2C insurance products.
- Build the APIs and design the data schema to fulfill the business requirements.
- Write tests and constantly seek to improve code quality and reliability.
- Drive the quality standards within the development team by example, produce highly usable technical documentation as well as conduct code reviews.

## 能力需求
- 2+ years experience of backend development.
- Familiar with Golang.
- Experience with RDBMS(PostgreSQL, MySQL), Redis.
- Experience with gRPC.
- Good knowledge of RESTful API design.
- Problem solving and critical thinking abilities.
- Enthusiastic about testing and performance.
- Willing to learn new tools, technologies, and frameworks to develop clean, testable, and maintainable components.
- Knowledge in CI/CD process.
- Familiar with git.
- Experience with building distributed systems and understanding microservices architecture.

## 加分能力
- Experience with Scrum/Agile methodology
- Familiar with WebSocket.
- Familiar with Docker/Kubernetes.

## 薪資範圍
1200K ~ 1800K / year (14個月保障月薪)

## 工時/特休
工時為每日 8 小時
加入第一天即享有年假，首年 15 天年假（依照入職比例發）
每年全薪病假 5 天、全薪生理假 3 天
2022 年多給 3天彈性休假

## 福利/推薦項
- 員工健康檢查補助
- 定期補充的零食以及飲料櫃、全新自動咖啡機、氣泡水機
- 社團活動費用補助
- 舒適的開放式工作環境，距離捷運台北101站 5分鐘路程
- Team building 經費
- 員工學習補助
- 彈性 WFH (依部門規定)

## 聯絡方式
可以透過 https://www.yourator.co/companies/OneDegree/jobs/18908
或是來信 howard.yeh@onedegree.hk

**Comment by appleboy** [comment]
月薪 10 萬以上的意思嗎？

**Comment by Hwrdy** [comment]
> 月薪 10 萬以上的意思嗎？

年薪結構是 14個月月薪, 所以月薪範圍約是 85K ~ 130K
