### ISSUE TITLE
[台北] [65K] COBINHOOD 柯賓漢數位金融科技 Trading Engine Infrastructure Developer

### ISSUE THREAD

**Issue by richardcwyo** [golangtw/jobs#12]
## 團隊簡介
COBINHOOD - Shaping future economies through cryptocurrency. COBINHOOD aims to become a financial center for the blockchain era. Maximize profit margins for traders all over the globe through our fee-free exchange.
https://cobinhood.com

## 工作地點
Xinyi District, Taipei City

## 工作內容
By joining COBINHOOD, You'll work on the bleeding edge of blockchain technology, including Bitcoin, Ethereum, and other cryptocurrencies, and play an important role in helping shape the future of how the world sees and uses the money.

COBINHOOD has the vision to become the largest and most successful cryptocurrency exchange in the world. Our Engineering team is having a blast while delivering the most sophisticated crypto-trading platform out there.  
Join COBINHOOD to meet the industry's future demand and lead the industry.

## 能力需求
+ 3+ years experiences in backend development 
+ 2+ years experiences in developing production-level application 
+ Experience in high throughput, low latency system design 
+ Experience in Kafka/ Cassandra distributed database system technologies 
+ Ability to debug complex systems and design solutions for it 
+ Familiar with designing RESTful APIs 
+ Strong knowledge in network protocols (TCP/IP/HTTP/HTTPS) 
+ Proficiency in Golang 
+ Experience with databases and SQL/NoSQL 
+ Experience in Linux 
+ Experience in AWS/GCP 
+ Experience in Kubernetes, Docker, DevOps and CI/CD procedures 
+ Knowledge in Bitcoin / Ethereum is a plus 
+ Passionate on new technologies 
+ Strong initiative and enthusiasm, self-motivated 

## 加分能力
+ Low latency or Real-time software development experience 
+ Data driven analysis and statistical modeling of problems 
+ Experience with financial algorithms or trading

## 薪資範圍
monthly NTD65,000 - 100,000  x 14

## 工時/特休
一到職即給7天特休

## 福利/推薦項
+ 公司近捷運象山, 101站
+ 彈性上下班，再也不用擠電梯擠車位了
+ 不打卡，不簽到
+ 休假制度優於勞基法：報到當日起即給與7天特休
+ 員工配股/員工認股
+ 每月點心櫃補到滿，想吃什麼自己點
+ 每位員工皆配備apple筆電
+ 彈性午休時間
+ 每週例行歡樂午餐時光，各種知名餐廳與美味餐點等著你
+ 豐厚獎金，肯拚就有收穫
+ 主管級員工椅及休息區，午睡時光讓你精力充沛

## 聯絡方式
cv/resume to careers@cobinhood.com

**Comment by appleboy** [comment]
公司解散 https://www.blocktempo.com/cobinhood-closure-of-business/
