### ISSUE TITLE
[台北][65K 以上] 酷堤康科技 - 資深後端工程師

### ISSUE THREAD

**Issue by jarvislin** [golangtw/jobs#124]
## 團隊簡介
酷堤康科技為印尼政府唯一支持的新創科技，同時有新加坡創投的投資，印尼辦公室座落於雅加達總統府行政區正對面（普通公司有錢也無法設立的地點）。

公司致力於打造印尼國家專屬聊天應用程式，同時與五百多個地方政府完成簽約，作為政府為一授權電子發票兌獎及發票獎金發放的管道。

台灣辦公室作為研發中心負責破億使用者的ＡＰＰ開發及跨國文化ＵＩ/ＵＸ設計，未來將延伸支付、電商、點數、貼圖、新聞等各種延伸服務開發。

團隊成員除了來自印尼與台灣兩地，還有來自韓國與馬來西亞的夥伴，歡迎所有想挑戰海外市場或想打造破億下載量的ＡＰＰ的夥伴們加入！

## 工作地點
台北市中山區（近捷運南京復興站）

## 工作內容
我們正尋找新的後端成員，一起參與新的產品開發、功能設計，持續優化其功能及系統架構， 使用 Golang 開發API、使用與維運 AWS 雲端服務， 歡迎您加入我們！！

## 能力需求
1. 有任一程式語言一年以上經驗 ex: PHP, Java, Node.js etc.
2. 願意學習 Golang
3. 有任一 RDBMS 使用經驗, ex: MySQL, Oracle etc.
4. 有任一 Cache 使用經驗, ex: Redis, Memcached etc.
5. 熟悉 Git / Git Flow
6. 理解 CI/CD 運作
7. 略懂 Docker
8. 對 RESTful 概念有清晰的理解
9. 熟悉XML / JSON / Protobuf 等至少任意一種網路通信技術和資料交換格式
10. 團隊合作、自我學習、跨部門的溝通協調能力

## 加分能力
1. 有任一 NoSQL 使用經驗, ex: MongoDB、DynamoDB etc.
2. WebRTC, SIP Server 相關經驗
3. MQTT / Socket 相關經驗
4. 熟悉 TCP/IP、HTTP 等網路通訊協定
5. Unit Test, Integration test, Functional test
6. AWS, GCP 相關經驗
7. 新創公司工作經驗

## 薪資範圍
65k ~ 85k 月薪 * 13

## 工時/特休
10:00 ~ 18:00

特休：
一、到職當年度，且滿三個月試用期後，七日。
二、一年以上二年未滿者，七日。
三、二年以上三年未滿者，十日。
四、三年以上五年未滿者，每年十四日。
五、五年以上十年未滿者，每年十五日。
六、十年以上者，每一年加給一日，加至三十日為止。

## 其他補充
目前 IndoChat 有 6 名 App 工程師、 2 名後端工程師、3 名設計師、2 名 PM、1 名 QA、1 名產品負責人；以下是身為工程團隊所看到的公司優缺點。

優點：
1. 目前印尼有 2.6 億人口，專案之後會由印尼政府推廣，使用者基數很可能超過千萬等級，此外也需要跨國協作，非常有挑戰性。
2. 每個人都有高度機會對產品帶來影響力。
3. 工時比其他公司少一小時，下班時有機會看到夕陽。
4. 就事論事不是口號，是真的做到想法直說不用擔心得罪對方。
5. 提供的硬體配備很高規，加起來大約台幣十萬。
6. 成員有自主學習能力，熱愛交流技術、參與過開源專案，我們有自己的讀書會，也曾有主辦社群活動之經驗。
7. 雖說是新創公司，但資金水位很充沛。
8. 學習補助給得很大方，買書、線上課程或國內 conference 門票可以申請補助。

缺點：
1. 由於疫情關係，產品尚無法在印尼大肆宣傳，因此目前使用者不多。
2. 公司在一年內從三人擴編到接近三十人，流程、制度會因規模而有所修改，目前也還在調整階段。

## 聯絡方式
CakeResume: 
https://www.cakeresume.com/companies/indochat-id-a24c49/jobs/sr-backend-engineer-senior-backend-engineer-golang

104: 
https://www.104.com.tw/job/7dc3w?jobsource=company_job

**Comment by appleboy** [comment]
補上 Label 了

**Comment by singer0503** [comment]
~~https://pro.104.com.tw/vip/job/jobmaster?jobno=12379532~~

104 的連結導向到後台，應該是這個連結~
https://www.104.com.tw/job/7dc3w?jobsource=2018indexpoc

**Comment by jarvislin** [comment]
> ~https://pro.104.com.tw/vip/job/jobmaster?jobno=12379532~
> 
> 104 的連結導向到後台，應該是這個連結~ https://www.104.com.tw/job/7dc3w?jobsource=2018indexpoc

thx, 已修正

**Comment by jarvislin** [comment]
已招滿，先關
