### ISSUE TITLE
[新北/五股][1M~1.5M/年] 仲琦科技 Backend Engineer (Golang)

### ISSUE THREAD

**Issue by liminghuang** [golangtw/jobs#147]
## 團隊簡介

仲琦科技為建立下一代雲平台服務，除了既有的新竹、蘇州研發團隊，計畫在台北成立另一個雲服務團隊，目前著重尋找後端的人才，台北團隊會是一個小而美的新團隊，沒有技術債的問題，目前已有接近百萬台設備上線，每個月持續成長中，歡迎喜歡挑戰從0開始的人才加入!

HitronCloud為一套雲端平台及應用程式解決方案，可管理家庭無線網路系統，並支援仲琦旗下纜線閘道器及 Wi-Fi 網路延伸器等一系列產品。HitronCloud 解決方案將自行設定並管理家中的寬頻及 Wi-Fi 網路功能，為網路服務供應商及終端網路用戶帶來直觀、智慧且便利的 Wi-Fi 服務。

更多關於公司請參考 https://www.hitrontech.com/zh-tw/

## 工作地點

新北市五股區五工五路38-1號 (暫時租借相關企業辦公室)

## 能力需求
Golang經驗3年以上，熟悉JSON/RESTful APIs，開發過high concurrency環境
資料庫經驗，SQL或NOSQL，例PostgreSQL、MongoDB，使用過Gorm
​建立過大型擴展分散系統，K8s容器、MQTT、微服務等相關技術
使用過AWS相關服務，ElastiCache/EKS等
3~5年以上軟體開發經驗，使用git
了解網路通訊、網路設備操作、閱讀英文技術規格文件

## 薪資範圍

NTD 1M~1.5M(年薪/15個月)
依能力可談更高

## 工時/特休
周一至周五 彈性工時 8:30-17:30/9:30 ～18:30
​優於勞基法特休天數，報到當天就有特休七天

## 福利/推薦項
全新Macbook Pro M1 14"+ 4K外接螢幕
免費汽車停車位
其它福利請參考 https://www.104.com.tw/company/a4blzsg?jobsource=company_job  (台北非地下停車場/無團膳)

## 聯絡方式

HR email: [Derong_Kong@hitrontech.com](mailto:Derong_Kong@hitrontech.com)

**Comment by appleboy** [comment]
@liminghuang 請提供月薪資訊

**Comment by appleboy** [comment]
月薪範圍 60K ~ 100K

**Comment by liminghuang** [comment]
關閉職缺
