### ISSUE TITLE
[台北/南港][月薪60K-120K] Intermediate/Senior Backend Engineer

### ISSUE THREAD

**Issue by elsalau-kk** [golangtw/jobs#148]
## 關於 KKTV

KKTV 是 KKCompany (KKBOX) 集團旗下的本土 OTT 品牌，成立於 2016 年。我們有全台最強日劇片庫以及動漫、韓台港陸泰劇、綜藝、紀錄片等眾多優質影音。我們致力於內容的探尋與挑選，深信人生中每個階段都有不容錯過的最新好戲與值得回味的經典好劇，並萃取其中值得探究的議題、引領人們以不同觀點品味劇中的精心安排，體驗不同時空背景的人生百態。同時我們也用心聆聽使用者的聲音，將他們給予的意見加以評估並落實在產品內，近年來推出的語言學習功能及共享方案都受到廣大用戶的熱烈好評！

## 團隊簡介

KKTV 產品團隊目前是由一個 scrum team 所組成，其中包含了 PM, Product Designer, Backend 及 Frontend 等成員，以兩週一個 sprint 的頻率進行開發。我們致力於維持開放透明的團隊風氣，讓成員們都可以瞭解並參與產品方向及功能的討論。歡迎有興趣和 KKTV 一起成長的你加入我們！

## 工作地點

台北市南港軟體園區二期（KKBOX辦公室）

## 工作內容

* Developing and maintaining video streaming and billing platforms.
* Optimize the service performance to provide better video streaming experience to audiences.
* Work with an agile product team to deliver business value. 

## 能力需求

* 3+ years of relevant cloud solution development experience (AWS preferred).
* Self-motivated communication skills, problem-solving skills and attitudes.
* Familiar with RESTful API design and development.
* Familiar with Golang.
* Familiar with AWS, especially Lambda and ECS.
* Experience with any SQL / NoSQL database (PostgreSQL / MySQL / Redis / etc.)

## 加分能力

* Familiar with Ruby on Rails.
* Experience with video streaming technology, CDN, and network performance tuning.
* Experience with database administration, and performance tuning.
* Experience with e-commercial billing systems.
* Programming skill in Node.js, Python (Legacy Code). 
* Experience with Jenkins, Gitlab CI, Terraform and Docker containers

## 薪資範圍

* 月薪 60K~120K，依能力敘薪
* 年薪保障 14 個月，不定期績效獎金

## 工時/福利

* 表定 09~18，彈性上下班（疫情期間視情況 WFH，目前採 AB 班分流）
* 優於勞基法的特休天數
* 免費使用 KKTV + KKBOX
* 不定期聚餐、Team building 活動
* 每週三固定有早餐或下午茶，辦公室常備吃不完的飲料、零食
* Last but not least - **Work-Life balance**

## 聯絡方式

可直接至集團招募網站投遞履歷：[連結](https://careers.kkcompany.com/kktv/a5486fb6-d0e7-43af-adb7-5288e68f288a)

**Comment by appleboy** [comment]
已加上 Label

**Comment by tonyhhyip** [comment]
@appleboy job position is closed

**Comment by appleboy** [comment]
@tonyhhyip OK. Got it.
