### ISSUE TITLE
[遠端][年薪1M - 1.6M] Bitmark 招募軟體工程師

### ISSUE THREAD

**Issue by JasonLiuBitmark** [golangtw/jobs#150]
[Bitmark Inc.](https://bitmark.com/) 是一個 fully distributed 的跨國新創團隊，要在台灣招募新血囉！

## 我們的產品
目前我們有兩個主要產品：
- [Feral File](https://feralfile.com/) -- A space for the new media community to co-create the future of art making, exhibiting, and collecting.
- [Autonomy](https://au.bitmark.com/autonomy-app/) -- The home for all your NFT art and other collectible.

## 職務內容
- Develop and maintain the backend and front-end (web, iOS, Android apps) of the products based on the [Bitmark Protocol](https://bitmark.com/protocol)
- Work closely with the team to build prototypes and validate solutions
- Work with communities to define and implement the standards of blockchain infrastructure
- Leverage CI and CD tools to automate testing and deployment
- Create internal data analytics and monitoring tools

## 我們尋找的特質
- Strong English communication skills
- Strong coding skills and computer science fundamentals
- We don’t discriminate by language, but having coded in Ruby, Python, Go, Java, Swift,... is a plus
- Knowledge of database (PostgreSQL, LevelDB, Redis,...) backed applications as used in REST APIs
- Knowledge of security and cryptography a big plus
- Knowledge of communication methods to interact with frontend applications (WebSockets, RPC,...)
- Knowledge of configuration management (git, Ansible,…) in a development environment
- Knowledge of container orchestration tools (docker, kubernetes,...) in a development environment
- You are creative and analytical, and like to be appreciated for both
- You are passionate about contributing to open-source codebases

## 關於 Bitmark Inc.
- 我們是一個設計與工程並重，並且擁抱 open-source 文化的團隊。[聽聽我們的成員怎麼說](https://hackmd.io/@bitmarkinc/rJ58-qmbY?fbclid=IwAR3mOcBHS6SGfYBvGQnxXEpL7JL_flTAC9Ol0AVA3USR_8Glf1V9b7qiBLA)在這邊的工作感想。
- 公司每半年做世界各地的薪資市場調查並且重新檢視我們的薪資。請參閱我們目前的[薪資以及員工配股公開資訊](https://hackmd.io/@bitmarkinc/Sy8VELsYF)。此職位年薪範圍在 NT$1M - $1.6M 之間。
- [員工福利](https://hackmd.io/@bitmarkinc/ryWUW97ZF) 包括健檢補助、 NFT 補助、部分 BTC 薪資、以及無上限的特休假。

## 聯絡方式
有興趣加入我們的話，請寄信至 careers@bitmark.com 並在標題欄中填上職缺名稱。歡迎分享你想要加入的動力。

**Comment by appleboy** [comment]
@JasonLiuBitmark 請提供月薪範圍？

**Comment by JasonLiuBitmark** [comment]
@appleboy , NT$1M - $1.6M, 已經更新囉。謝謝！

**Comment by appleboy** [comment]
@JasonLiuBitmark 所以我可以認為大約是月薪 90K 以上嗎？

**Comment by JasonLiuBitmark** [comment]
> @JasonLiuBitmark 所以我可以認為大約是月薪 90K 以上嗎？

此職缺我們會依照資深程度分為 Staff 跟 Lead 兩個不同的等級。目前月薪分別為：
- Staff 月薪為 NT$86,875
- Lead 月薪為 NT$132,500

我們每半年會重新評估市場薪資資訊及公司營運狀況調薪。

**Comment by appleboy** [comment]
@JasonLiuBitmark  感謝提供，資訊非常清楚
