### ISSUE TITLE
[台北/信義][月薪6萬以上][M800 台灣資信] Jr. Backend Engineer - golang

### ISSUE THREAD

**Issue by eaglerayp** [golangtw/jobs#151]
## 團隊簡介

公司名稱:
M800 Taiwan Limited 台灣資信有限公司
統編: 50766514
公司網址: https://www.cinnox.com/
104 職缺頁面: https://www.104.com.tw/job/653o3?jobsource=company_job

香港電信商 M800 於 2007 年由一群電信先驅創立而成，旨在徹底改變全球通信，致力於幫助全球各地的企業應對最棘手的通信挑戰。
台北研發團隊正致力於 cinnox 企業解決方案的產品實作。

主要服務項目:
[cinnox]
開創性融合數據平台 cinnox 為企業提供內部協同通訊及客戶服務體驗的全面通訊解決方案。
cinnox 以創新的多維融合模型為設計核心，能夠高效整合多個通訊管道，包括 PSTN 及 VoIP 電話，網站，應用程序和社交媒體。

## 工作地點

台北市信義區信義路五段7號45樓C區 (101 辦公大樓 45F C區)

## 團隊技術

* 使用 gitlab 進行版本控制及審核
* Devops 使用 Jenkins 建立 pipeline 進行自動化測試與部署，terraform 處理 AWS 自動化部屬。
* 使用 Go 語言開發商業邏輯，後端系統目前採行 micro services架構
* 基礎建設: Kubernetes Cluster，並有多個環境供測試，開發及壓力測試。
* 生產環境建於雲端: AWS 和 Aliyun，滿足全球化客戶需求
* 使用 MQTT， Restful API ， websocket 與前端互動
* 資料庫使用 MongoDB, Redis, MariaDB, VaultDB
* Message Queue/pub-sub service: Kafka, [nats.io](https://nats.io/)
* 使用 Grafana + Prometheus + Alert Manager 監控服務狀態

## 職涯提升與組織內升遷制度

* 每月固定與主管 1-1 確認表現/成長/感受，對齊工作短期與長期目標和職涯規劃
* 依績效，每半年即有一次提名升遷的機會
* 升遷會伴隨明確有感加薪和績效標準改變

## 工作內容

* 設計和開發商業邏輯 API 與前端（web/iOS/Android） 互動
* 維護現有的後端功能包括但不限於：即時通訊、SMS、email、MQTT、cloud storage (AWS/阿里雲)、Mobile Push、外部系統整合、任務分派系統、計價、資料分析和搜尋引擎。
* 研究相關領域新知，保持知識分享團隊文化
* 以 project team (scrum) 形式與前端開發人員，UI/X 設計，QA 以及 PM/PO 協作。系統維護方面與 OP/IT/CICD/SRE 等團隊共同促進系統穩定度。 

### First month Expectation

* 了解團隊運作現狀，團隊目標，摸索目前產品功能。
* 搭建自己的工作環境，熟悉當前的部屬環境與 git policy。
* 學會 golang，(如果原本不會的話)。
* 藉由 code review，了解團隊的 coding pattern 和設計原則。
* 在 mentor 的協助下，完成交付的工作。
* 與主管確認試用期(前三個月)通過標準。

### First three months Expectation

* 進入 Feature 專案開發團隊，在 senior member 的帶領下交付專案。整個專案過程會參與需求確認、討論、系統分析、實作開發、測試、部屬。
* 藉由開發過程了解團隊運作，team code pattern，縮短 code review gating period。
* 與主管定期 1-1 確認狀況，確保熟悉團隊方向，滿足試用期通過標準。

### First six months  Expectation

* 從專案開發經驗能慢慢接手做部分component owner，或是成為 component backup。
* 能處理負責範圍內 e2e 的 issue，能協調PM和前端同事共同解決問題。
* 持續參與團隊流程和活動回饋，促使團隊持續進步。
* 與 Team Lead 討論下一階段的職涯規劃。

## 能力需求

* 熟悉至少一種主流後端程式語言 (C++, python, php, java, golang, ruby)
* 熟悉至少一種 SQL, NoSQL 資料庫操作與 schema design
* 基本版本控管概念 (Git)

## 加分能力

* 熟悉 Golang 。
* 了解 Linux 底層，網路/資安理論， Docker 及 Kubernetes 相關技術
* 具有專案協作概念，經歷
* 熟悉單元測試和 TDD 等概念

## 薪資範圍

* 最低月薪60k以上，依能力面議

## 工時/特休

* 每日工作時間: 9:00 AM ~ 6:00 PM  中午休息(12:00~1:00)
* 加班費制度： 呈報加班費，計算比照勞基法，不常態性加班
* 試用期滿三天，第一年即享有 10 天年假

## 聯絡方式

Mike Duh
E-mail: mikeduh@m800.com
標題請註明 應徵 M800 Backend Developer
履歷夾帶於 email 附件

**Comment by appleboy** [comment]
已經上 tag
