### ISSUE TITLE
Go

### ISSUE THREAD

**Issue by debbie0204** [golangtw/jobs#152]

**Comment by debbie0204** [comment]
> // 以下是建議填寫項目，可自由增刪排序~ // 也建議標註團隊目前技術框架 // ^ 上面的看完就可以刪了~
> 
> ##團隊簡介 韋博科技專注於研發各類型的數位遊戲與專業企業內部系統，我們獨特、創新、追求卓越， 結合最新最頂尖的技術，堅持打造高水準的產品。 在這裡，您可以盡情發揮創意，與優秀的團隊共事，並一起探索各種領域，一起創造出最獨特且前所未有的感動。
> 
> ## 工作地點
> 新北市板橋區曼哈頓金融大樓
> 
> ## 工作內容
> 1. 一年以上的Golang開發經驗，熟悉主流應用架構。
> 2. 有撰寫Unit test、壓力測試等經驗。
> 3. 有多人Git協作開發經驗。
> 4. 有MySQL、PostgresSQL等至少一種數據庫的使用經驗。
> 5. 對數據庫SQL、Redis、Mongo等有一定知識。
> 6. 熟悉Linux、Git使用流程的操作。
> 
> ## 加分能力
> 【加分項目】
> 
> 1. 有SQL調教經驗。
> 2. 遊戲開發或維護經驗。
> 3. 遊戲API、遊戲後台等相關經驗。
> 4. 有使用過RabbitMQ。
> 5. 有高併發、高可用、分散式服務開發經驗者為佳。
> 6. 有CI/CD佈署經驗。
> 
> 【特質要求】
> 
> 1. 能理解遊戲設計並進行架構設計及開發。
> 2. 撰寫穩定可靠、高效且可維護的程式代碼、測試並修復程式錯誤，並接受關鍵反饋和進行改善。
> 3. 善於溝通、有領導經驗，個性積極、喜歡挑戰。
> 
> ## 薪資範圍
> 月薪 60K~120K，依能力敘薪 年薪保障 13 個月，不定期績效獎金
> 
> ## 工時/特休
> 彈性上下班，9:00-10:00上班~18:00-19:00下班
> 
> ## 福利/推薦項
> 法定項目 三節獎金 生日禮金 年終獎金 優於市場行情的薪資待遇
> 
> 豐富的聚會活動，讓您吃喝玩樂都開心～ 年終尾牙 員工聚餐 電影欣賞 家庭日 自強活動 部門聚餐/活動 員工旅遊 健康檢查
> 
> 教育訓練提升您的競爭力～ 各項教育訓練規劃與安排
> 
> 優質的環境讓您工作事半功倍～ 典雅舒適的工作環境 無限量咖啡零食茶點供應
> 
> ## 聯絡方式
> 檢附履歷、自我推薦信以及作品集等有利資料，以應徵_Senior Backend Engineer (golang)_(你的名字) 為主旨，寄至 [weipohr@gmail.com](mailto:weipohr@gmail.com) 或可以直接至我們的求職平台投遞履歷104：https://www.104.com.tw/company/1a2x6bkzf5



> 

新北板橋 60K以上

**Comment by debbie0204** [comment]
@appleboy 請幫我added 台北60K以上labels，謝謝

**Comment by debbie0204** [comment]
@appleboy 請幫我added [台北]( [60K以上]labels上去，謝謝你^^

**Comment by appleboy** [comment]
@debbie0204  已經補上 label

**Comment by appleboy** [comment]
@debbie0204 最低是 50K 所以我改成 50K 的 label

**Comment by debbie0204** [comment]
@appleboy 請幫我added [台北]( [60K以上]labels上去，薪資有做修改，謝謝你^^

**Comment by debbie0204** [comment]
please delete this article,thanks
