### ISSUE TITLE
台中-PYTHON工程師

### ISSUE THREAD

**Issue by LindaWU7788** [golangtw/jobs#156]
## 工作地點
台中市西屯區

## 工作內容
你有經驗按一個按鈕就可以完成數百千的資料的處理嗎？
你喜歡養機器人嗎？
目前的資訊環境有太多事情要確認要執行，你有想利用
程式來完成你的日常工作嗎？
歡迎加入我們!!!!

1.平台開發與維護
2.串接第三方服務
3.客製化系統開發

## 能力需求
1.使用Python進行相關開發應用及模組
2.熟悉MongoDB、RabbitMQ、Redis..等服務

## 薪資範圍
面議

## 聯絡方式
the.win13888

**Comment by appleboy** [comment]
這邊是 Golang 徵才區
