### ISSUE TITLE
🔥創業夥伴 [台北/遠端][技術股+底薪] 酷卡科技股份有限公司 - Golang 工程師

### ISSUE THREAD

**Issue by oscar-ko** [golangtw/jobs#182]
創業比我想像的辛苦很多，沒人，沒錢，沒資源，很希望找到想一起創業的朋友
▍工作內容
職位：Golang 工程師 
前端透過 GraphQL 與 Server 溝通。ChatGPT、Bard API …串接
可遠端工作，但必要時還是需要見面討論與規劃
▍薪資
$40,000(現金) ＋ 40,000(股權) + 勞健保
▍公司介紹
酷卡科技（台北）是我為了興趣而成立的公司，專注在「個人AI學習」及「企業AI應用」，很幸運我在FB找到幾個伙伴一起創業。應用於語言學習的「酷卡英文」iOS 版已經上線一年，每天有穩定的下載量，目前也有完整的商業模式。透過個人端AI應用的經驗累積，目前企業端的「AI指令管理平台」也正在開發中。我們公司目前已獲得一項專利，也已取得 SiTi臺北市產業發展獎勵補助計畫。
▍聯絡方式
如果你想要有一份屬於自己的事業，也對我的夢想有興趣，那麼歡迎你FB私訊我，或 oscar.ko@coolcard.app。
FB： https://www.facebook.com/oracle.oscar 
![截圖 2023-09-18 下午5 38 48](https://github.com/golangtw/jobs/assets/33344160/ba254225-7161-46b0-86e4-65920a325f15)

**Comment by appleboy** [comment]
duplicated of https://github.com/golangtw/jobs/issues/123

**Comment by oscar-ko** [comment]
@appleboy  I closed all related issues and posted a updated one.
