### ISSUE TITLE
[新竹/竹科] [月薪 10 萬起] [年薪 200 萬] 聯發科技資深軟體工程師

### ISSUE THREAD

**Issue by appleboy** [golangtw/jobs#196]
## 工作地點

新竹科學工業園區篤行一路 2 號 (聯發科總部 V 棟)

## 團隊簡介

* 聯發科技專注於使用 AI, BigData, Process Automation 技術提升公司各部門團隊生產力，及改善 IC Design Flow
* 擁抱產品及數據思維，以數據驅動產品功能之開發決策
* 以使用者故事 (user story) 作為開發依據，採用敏捷式開發 (Agile development) 快速迭代產品
* 重視團隊成員能力成長及團隊向心力，每月由不同成員定期做軟硬技術分享 (AI / BigData / Process Automation)，進而達成組織目標
* 自動化測試部署確保軟體品質及提升工作效率減少時間浪費

## 基本條件

* 有 Go 語言或類似經驗，熟悉 gRPC 及 RESTful API
* 有能力根據設計原則 design principles 及設計模式 design patterns 寫出 clean, maintainable, and performant code
* 有建立大型且可擴展分散式系統，能理解熟悉微服務架構，Kubernetes，容器等相關技術
* 有使用 Kibana、Loki、Grafana、Tempo、OpenTelemetry 和 Prometheus 等可觀察性、監控、警報、追蹤和日誌記錄工具的經驗。
* 能夠指導團隊合作整體設計和程式碼架構，並不斷努力改進它，能夠為團隊編寫風格指南以供遵循。
* 五年以上相關軟體開發經驗，資工/電機相關科系畢業

很多會問，什麼條件才能成為資深軟體工程師，請直接參考這篇文章『[如何才有資格稱為資深工程師](https://jaceju.net/be-a-senior-engineer/)』

## 工作內容 

1. 規劃後端微服務架構
2. 自動化流程部署設計
3. 線上服務維護與除錯

## 團隊技術

1. 使用 [Gitea][10] 進行版本控制及審核
2. 使用 Jira 及 Confluence 控管專案進度及文件
3. 使用 [Gitea Action][11] 打造自動化部署系統
4. 使用 Go, Python, Node.JS 語言開發微服務架構
5. 使用 Restful API, GraphQL 或 gRPC 進行服務溝通
6. 資料庫使用 SQLite, Postgres 或 MySQL
7. 雲平台使用 Azure, AWS 或 GCP
8. 透過 [Terraform][12], [Pulumi][13] 管理 Infrastructure
9. 使用 Grafana + Prometheus + Loki 監控各種服務狀態
10. 使用 Kubernetes 部署服務
 
[10]: https://about.gitea.com/
[11]: https://docs.gitea.com/usage/actions/overview
[12]: https://www.terraform.io/
[13]: https://www.pulumi.com/

## 薪資福利

年薪百萬起跳 100k/month（依據資歷能力給薪）

* 年終兩個月(依照到職比例)
* 健康檢查 (6500 元)、聚餐補助
* 旅遊補助 16000 (每年) 可以買任何產品
* 午餐跟晚餐補助 65 元 (分開補助)
* 每個月 200 元餐點補助 (7-11, 星巴克購物)

## 聯絡方式

請將履歷夾帶於附件，寄信至 Bo-Yi.Wu@mediatek.com，標題註明『`應徵聯發科技後端工程師 - XXX`』(其中 XXX 為姓名)， 我們將會與您聯絡

**Comment by chengr4** [comment]
bo-yi 大，「透過 [Terraform](https://docs.gitea.com/usage/actions/overview), [Pulumi](https://www.terraform.io/) 管理 Infrastructure」的連接是錯的

**Comment by appleboy** [comment]
@chengr4 Fixed，感謝告知

**Comment by jack482653** [comment]
信息服務 -> 訊息服務
分布式 -> 分散式

**Comment by appleboy** [comment]
@jack482653 Thanks for your feedback. Fixed.

**Comment by aiii8kuu** [comment]
貴單位不太尊重應徵者, 朋友上個月面試三關結束後通知錄取, 協調好到職時間等走核薪流程約兩週, 主管還特地傳簡訊通電話恭喜歡迎他, 還建議到職前練Golang做準備等等, 朋友還傻傻準備等待, 兩週後竟然連取消也沒有通知, 有時間在平台重開職缺, 卻連電話簡訊郵件的詢問都沒有回覆, 連委婉拒絕的禮貌都沒有直接不演 
雖然說口頭offer的確沒有實質效力, 但只能說處理的方式蠻差勁的
