### ISSUE TITLE
[台北] [90K以上] [書亞集成] 資深網頁後端工程師 (Senior Web Back-end Engineer) 

### ISSUE THREAD

**Issue by appleboy** [golangtw/jobs#2]
![19274929_10207306366216831_1439370489865731627_n](https://user-images.githubusercontent.com/21979/27318840-ec37f294-55c0-11e7-972e-96840007fe53.jpg)

本文轉自: [【 誠徵資深網頁後端工程師 (Senior Web Back-end Engineer) 】](https://www.facebook.com/yftzeng.tw/posts/10207306064529289)

為即將推出的新產品 / 擴展的新市場，誠徵新同事。我們同時也徵資淺工程師，需求不需達到後述【專業需求】的每個等級，有興趣歡迎來信聊聊。

## 團隊簡介

[書亞集成股份有限公司](http://www.surasia.net/) ( 請 Google "書亞集成" )(面試時我們也會更詳細介紹公司)

## 工作地點

臺北市松山區 (近臺北中山國中捷運站，走路約 7 分鐘)

## 工作環境

➀ 可配至少二個大螢幕。
➁ 相對彈性的上下班制度。
➂ 免費多項公司內部訓練，包括網頁前端、後端、資料庫、資訊安全、法律及創業等。
➃ 免費多次員工聚餐。
➄ 除了實際應用外，我們也很重視新技術的研究與學習。
➅ 公司請你不是要你聽命行事，而是要把事情做好，若覺得公司管理有可議之處歡迎隨時反應。
➆ 嚴禁常態加班，公司請你是要做對的事而不是燃燒生命，身體搞砸對公司只有壞處沒有好處。我們非常瞭解工程師常態加班只會產出壞程式。
➇ 公司不需也不會向您索取先前工作的薪資證明，更不會以先前工作的薪資作為參考。您必須對您的薪資感到滿意，工作才會愉快。
➈ 我們有相對完整的公司內訓計畫，目標讓每位同仁都能成為[資深工程師或軟體架構師](https://blog.gcos.me/enterprise_trainings.html )。

## 工作內容

➀ (必備) 對至少一項程式語言有足夠瞭解的信心。(我們目前使用 PHP 及 Golang)
➁ (必備) 熟悉網際網路基本常識。包括但不限於 TCP/IP、DNS、HTTP 等。
➂ (必備) 瞭解 Linux 作業系統基本安裝及效能增進。包括但不限於 Networking、Scheduling、FileSystem 等。
➃ (必備) 瞭解 Git / GitHub，包括但不限於分支操作、衝突解決及 Pull Requests。
➄ (必備) 瞭解資料庫 (MySQL / PostgreSQL / MongoDB / Cassandra / Redis 至少其一) 安裝、設計、效能增進及除錯。
➅ (必備) 熟悉系統架構設計。具備依據需求獨立設計系統架構的能力，瞭解不同架構所適用的情境並作出調整。
➆ (必備) 熟悉資訊安全。包括但不限於 Hijacking、Injection、XSS、CSRF、SSRF 等。
➇ (加分) 熟悉雲服務的建置與維運。(AWS and/or GCP and/or Azure and/or Linode)
➈ (加分) 熟悉大數據平台建置。(Hadoop / Spark / Hive / Flink / Beam etc.)
➉ (加分) 熟悉 DevOps。能善用 Continuous Integration / Continuous Deployment。
⑪ (必備) 熟悉高效後端操作與控制，如高併發、延遲處理及分布式設計。
⑫ (加分) 擁有組織大型專案結構的技巧及經驗。

## 能力需求

➀ (必備) 具備鍵盤盲打之技能。
➁ (加分) 英文打字至少每分鐘 30 字，中文打字至少每分鐘 40 字。
➂ (必備) 熟悉 command line (命令列) 操作。
➃ (必備) 對新技術有熱情及渴望，有信心可獨立完成專案。
➄ (必備) 良好的邏輯及溝通能力，當責不卸責。
➅ (必備) 熟悉後端開發流程，懂得程式檢查、精簡化、模組化。
➆ (必備) 懂得編寫清晰易懂且容易維護的程式碼。

### 第一階段：

➀ (非居住於台北市或新北市者，或有其他原因者) 視訊或 Email 訪談，初步瞭解雙方需求。
➁ 邀請您實際參訪本公司。
➂ 公司介紹，包括團隊及工作內容。
➃ 自我介紹，積極表現過去工作態度、經驗、專案及績效成果。
➄ 考題測驗，可能需要上機撰寫程式碼，也可能僅需要書面作答。
➅ 雙方互答。

### 第二階段：

➀ 第一階段面試結束後，由公司等待您的意願回覆。
➁ 第二階段由應徵者決定是否願意與我們共事，不是無禮的單向寄發錄取或不錄取通知。畢竟公司與應徵者是平等的，公司面試人，應徵者也在面試公司。
➂ 此階段無須再至本公司一趟。

### 第三階段：

➀ 若有榮幸獲得您的意願，公司會從眾多回覆者中，挑選出本次面試中選者。
➁ 無論是否中選，公司都會寄發通知信。
➂ 此階段無須再至本公司一趟。

以上，為不浪費寶貴時間，面試流程只需(仍需)參訪公司一次的原因如下：

➀ 與未來可能共事的同仁會面，這很重要，第一面是否感覺好相處的同事是您決定是否願意與我們共事的關鍵之一。相對而言，我們同事也可以感受您是否好相處。
➁ 感受公司配置及裝潢所展現出來的氣質與文化。從動線、擺設及空間利用率，可決定一間公司對於員工環境的重視度。例如有些公司為容量更多人，讓空間都變成座位，導致走道狹小，動線不佳，員工也沒有合適的休閒空間。
➂ 順便瞭解公司附近的生活機能，包括食衣住行等。
➃ 符合以上條件，故只需來訪公司一次即可，無需舟車勞頓。

## 薪資範圍

月薪: **NTD $900,00 以上**

## 工時/特休

嚴禁常態加班，公司請你是要做對的事而不是燃燒生命，身體搞砸對公司只有壞處沒有好處。我們非常瞭解工程師常態加班只會產出壞程式。

## 聯絡方式

▐ 來信請寄至 < yftzeng@gmail.com >。
▐ 信件主旨開頭請為：【應徵網頁後端工程師】OOO (OOO 請用您的名稱取代之)。
▐ 履歷或作品附件請用標準 PDF 檔案寄送。
▐ 若您苦於履歷表設計，我們建議您可以參考 https://jsonresume.org/ 免費線上履歷表。
▐ 面試前應詳閱本徵才需求，請務必區分(必備)及(加分)項目，注意【熟悉】及【瞭解】用語的差別。(加分)僅提供面試分數調整，非面試必要門檻條件。
▐ 我們尊重任何人的個資、隱私及性向，所以履歷不需包括您的年齡、身高、體重、地址等資料。也請不要寄送 104 制式履歷給我們，因為它會洩露您的隱私。
▐ 為保護每位面試者隱私，公司未額外保留個人資料及聯絡方式，所以無法也不能主動聯繫先前面試的優秀人選。然您可能因我們當下職缺有限，或我們當時不足以提供您滿意的薪資，或公司發展不適合面試者職涯考量。以上原因也許時至今日已解決，所以我們隨時歡迎二次以上的面談機會，也感謝您願意再給我們一次機會。

## 其他事項

以下為我們對外公開的技術分享簡報，供您參考。

➀ [善用 MySQL 及 PostgreSQL - RDBMS 的逆襲](https://www.slideshare.net/yft…/mysql-postgresql-rdbms-part1)
➁ [恰如其分的 MySQL 設計技巧 Modern Web 2016](http://www.slideshare.net/yftzeng/mysql-modern-web-2016)
➂ [談 Uber 從 PostgreSQL 轉用 MySQL 的技術爭議](http://www.slideshare.net/yftzeng/uber-postgresql-mysql)
➃ [資料庫索引數據結構及主鍵設計 (b+tree)(part 1)](http://www.slideshare.net/yftzeng/btreepart-1)
➄ [Enterprise Architecture Case in PHP (MUZIK Online)](http://www.slideshare.net/yftzeng/enterprise-architecture-case-in-php-muzik-online)
➅ [Redis, another step on the road](https://www.slideshare.net/yftzeng/redis-another-step-on-the-road)
➆ [淺入淺出 MySQL & PostgreSQL](http://www.slideshare.net/yftzeng/mysql-postgresql)
➇ [PHPConf.TW 2012: A step to better PHP](http://www.slideshare.net/yftzeng/php-conf-tw2012ant)
➈ [(前端) 工程師面臨的資安挑戰-前傳](https://www.slideshare.net/yftzeng/2013-0413-jstwsecurityforfrontendengineeringprequel)
➉ [(前端) 工程師面臨的資安挑戰-後傳](https://www.slideshare.net/yftzeng/jsdc-2013frontendengineeringsecurity)

若為達人，您來我學；若想達人，您來我教。歡迎轉載、跳坑及推坑。

**Comment by henrynet** [comment]
薪資範圍 > 月薪多了一個零吧XD...

**Comment by appleboy** [comment]
@henrynet 已經修正，感謝告知 👍

**Comment by diabloevagto** [comment]
本文轉自: 【 誠徵資深網頁後端工程師 (Senior Web Back-end Engineer) 】
其中的連結已經失效了

**Comment by appleboy** [comment]
對，我晚點問一下作者要不要關掉這職缺
