### ISSUE TITLE
[台北] [80K以上] [OneAD 果實夥伴] Golang Engineer

### ISSUE THREAD

**Issue by jimmykuo** [golangtw/jobs#22]
## 團隊簡介

[OneAD](http://www.onead.com.tw/) 是台灣唯一專注於影音廣告的科技公司。我們擁有貫穿影音廣告產業所需完整的關鍵技術能力，從 CDN, Video Delivery Management, OVP, Encoding/Transcoding, Video Ad Server, ERP, Programmatic, Data Science 等，我們正在改變這個產業的生態鏈，提供桌機、行動、和連網電視等多屏幕影音廣告雲端平台的運營。
  
我們聰明地運用科技的力量，以優異的廣告技術能力與頂尖的優質網站合作，建立全台最大覆蓋的影音廣告聯播平台。
  
我們服務百大廣告主，在多屏幕的新媒體世代解決廣告主品牌溝通的需求。透過海量數據的收集和分析，幫助品牌在網路上達到最佳的影音廣告溝通成效！是全台最大的影音廣告大媒體！

## 工作地點

台北市內湖區瑞光路 (近西湖捷運站)

## 工作內容

開發廣告推播服務

## 技能要求

- 2 年以上後端開發經驗
- 熟悉一項強型別語言
- 熟悉 Linux 操作及系統優化
- 熟悉 MySQL 或是其他 RDBMS 的安裝、效能調整。

## 能力需求

- 樂於團隊溝通與良好協調能力、工作態度積極、勇於接受挑戰、抗壓性高
- 獨立，有效率並能如期完成工作
- 高度學習能力與適應新的工作責任
- 渴望了解新的技術，並不斷用於改善舊有的系統

## 加分能力

- 使用過 Google Cloud Platform 或 AWS 各項服務
- 使用過 redis/memcached/cassandra/kafka/flink
- 對基本的 DevOps (CI/CD) 有概念
- 對常見的安全性議題 (xss, sql injection, csrf) 有概念
- 有大型系統架構和開發經驗，熟悉高負載架構及大流量服務器架構及優化

## 薪資範圍

80,000/月 (起)

**所有的條件都非絕對必要，只要您對 golang 有興趣，都歡迎寄送履歷給我們。**

## 聯絡方式

履歷可直接投到 [104](http://bit.ly/onead104) 或是寄送到 ([jimmykuo@onead.com.tw](mailto:jimmykuo@onead.com.tw))，謝謝大家!

**Comment by jimmykuo** [comment]
謝謝大家，暫時停止收件
很多朋友過來聊天，收獲不少呀~ 😄 

謝謝 @appleboy 提供這個 jobs 版 👍

**Comment by appleboy** [comment]
@jimmykuo 不會啊，希望大家都可以找到好人才。我先關閉了喔。如果有其他需要再打開或者是新開 issue。
