### ISSUE TITLE
[台中][40K+] 長青資訊有限公司 Golang Backend Engineer

### ISSUE THREAD

**Issue by Hq213** [golangtw/jobs#28]
## 工作地點
台中市西屯區朝富路213號30樓(長青資訊有限公司)

## 工作環境與該職缺團隊介紹:
  - 公司位於台中七期金融核心，辦公室位在頂級國際商辦大樓，環境舒適且視野遼闊
  - 公司有專業的研發及設計團隊作為後盾，追求最佳品質不間段的研發創新技術
  - 放眼國際市場，事業版圖與推廣區域已拓展至中國、越南、印尼及中南美洲等地

## 工作內容
協助專案開發及活動製作

## 能力需求
基本條件:
  - 熟悉 Golang
  - 熟悉 Restful Api 格式
  - 熟悉 MariaDB ，MongoDB，Redis 或其他相關資料庫

## 加分能力
  - 熟悉微服務系統架構
  - 熟悉 Docker 操作與應用
  - 熟悉 Docker 任一編排工具，如(Docker Swarm , k8s , Mesos 之一即可）
  - 熟悉 Linux 系統操作
  - 參與開源項目
  - 參與過大型專案開發項目
  - 有過敏捷開發項目經驗
  - 善於系統分析與設計
  - 具備獨立思考能力
  **開發語言以Golang為主，擅長PHP者也歡迎嘗試

## 薪資範圍
40,000-70,000以上，依照經驗能力談薪
薪資(保證最低年薪  13個月)

## 工時/特休
每日工作時間: 09:00 ~ 18:00 (7.5小時)  中午休息(12:00~13:30)
  每周工作時間: 7.5*5=37.5
  週休二日、見紅就放

## 福利/推薦項
- 每天一小時彈性上下班時間，不必和打卡鐘賽跑
  - 免費療癒的午茶及員工餐廳，天天都有充沛活力
  - 具競爭力的調薪和升遷制度，用心絕對會有代價
  - 各種主題的教育訓練，重視員工的發展及獨特性
  - 不定期舉辦聚餐、旅遊等活動，感受團隊凝聚力
  - 定期進行員工健檢，善盡監督員工健康的責任

公司分紅與獎金:
  - 每季績效獎金發放，平均一季領0.5個月
  - 介紹獎金，員工介紹公司需求人才後可獲得之獎金

## 聯絡方式
電話:04-2258-6177(KIM小姐)
Email :kimkimberry0607@cchntek.com

**Comment by appleboy** [comment]
公司名稱是?

**Comment by Hq213** [comment]
長青資訊有限公司

**Comment by appleboy** [comment]
@Hq213 幫忙修改標題了。

**Comment by Hq213** [comment]
謝謝你

**Comment by Hdoreen0340** [comment]
@appleboy 
您好~我是長青資訊的HR Doreen，
是否可以請您協助把此篇職缺訊息下架，
因為之前負責人員 @Hq213 已離職，註冊之信箱也已註銷，
此篇Golang後端工程師的職務內容及公司簡介有多處須更新資料，
我會重新在po上新的一篇職缺訊息，感謝您!!

**Comment by appleboy** [comment]
@Hdoreen0340 好的

**Comment by Hdoreen0340** [comment]
@appleboy 謝謝您
