### ISSUE TITLE
[台中][40K+][亞西亞龍] 後端工程師 Backend Developer

### ISSUE THREAD

**Issue by ShirleyLo** [golangtw/jobs#31]
## Asialong集團簡介
![AsiaLong](https://raw.githubusercontent.com/a2n/temp/master/AsiaLong.jpg)

亞西亞龍秉持著創新、品質、服務之核心理念，立志打造世界遊戲王國，每項產品皆經過嚴格考驗，只帶給您最完美的作品。並在技術與服務品質多次榮獲國際玩家肯定，但我們並不因此自滿，近年更引進日韓與歐美地區技術，無論是軟硬體或技術層次都更上一層樓，除此之外，我們更不斷蛻變，將健康、休閒、娛樂元素帶入設計理念中，讓廣大的會員在繁忙的生活中，亦能注入新活力，隨時隨地享受娛樂，體驗更高品質的遊戲。

*  以誠信和團隊合作的精神，透過專業的經營模式，堅守每個專業領域，全心投入，追求盡善盡美，創造卓越與成長。
*  獨特技術、創新玩法，展現致勝的關鍵，並不斷研發設計，提供完善的遊戲品質。
*  以高標準的「安全」、「便利」兩大原則，研發快捷的網路服務、行動裝置應用為目的，期望能滿足消費者需求，深獲社會大眾的信賴與支持！ 
*  堅守產品品質，以客戶服務導向；提供客戶及時、及地的服務，滿足客戶需求。無論在品質、技術、速度配合，我們立霸為客戶端提供全方位的服務。

## 公司網站
https://www.asialong.info/

## 工作內容
開發厲害的程式 :laughing
快來達成 C10M 成就 :rocket

## 能力需求
0.  實作 RESTFul API 經驗 
0.  熟悉 MySQL、Redis 
0.  熟悉 Linux 操作 
0.  有 WebSocket 實作經驗 
0.  有 HTTP 併發經驗 

## 加分能力
0. 系統設計經驗 
0. 併發處理經驗 
0. AWS / GCP 使用經驗 

## 薪資範圍
月薪 4w ~ 7w

## 工作地點
[臺中市西區台灣大道二段573號9樓A室](https://www.google.com.tw/maps/place/403%E5%8F%B0%E4%B8%AD%E5%B8%82%E8%A5%BF%E5%8D%80%E5%8F%B0%E7%81%A3%E5%A4%A7%E9%81%93%E4%BA%8C%E6%AE%B5573%E8%99%9F/@24.1573587,120.657756,18.83z/data=!4m5!3m4!1s0x34693d9b2b48b46f:0xe951f087551f588d!8m2!3d24.1576043!4d120.6576519)
➤➤ 位於精誠公益商圈，各式美食任君挑選 :beers: :curry: :bento: :icecream:

## 工時/特休
彈性上下班，09:00 ~ 17:30，7.5 小時
午休，12:30 ~ 13:30

## 福利/推薦項
➤年資滿半年，享有四天特休假
➤專心工作、輕鬆的上班環境、彈性上下班30分鐘
➤Philips Saeco全自動咖啡機，奶茶、歐蕾、義式、拿鐵隨意喝
➤不定期國內外大型展覽觀展機會、國內旅遊補助
➤不固定多樣化的其他活動：健行、烤肉BBQ…等
➤不定期在職訓練
➤每月新增書籍雜誌，皆可借閱

∆達成年度目標通通有獎
∆公司WiFi上網、Happy Hour上班玩耍時間
∆不定期聚餐、年度聚餐、部門聚餐
∆年度優質健康檢查
∆本公司遵行勞基法與勞健保相關法令保障

## 聯絡方式
*  [Email](mailto:hr@along899.com) 
*  [104](https://www.104.com.tw/jobbank/custjob/index.php?r=cust&j=4e4c446d3a6e4b69586a3c673240386193a3c446d363840693e443c1f1f1f1f1e14662382a67j01)

**Comment by appleboy** [comment]
應該補上底下需求會比較好:

> 1. 熟悉 Golang 語言特性，熟悉內建框架，且對 Go 有極大學習興趣。 
> 2. 了解 Linux 作業系統特性，指令操作介面。 
> 3. Git 操作，Bitbucket 作業。 

ref: https://www.104.com.tw/job/?jobno=62d9u&jobsource=

**Comment by a2n** [comment]
此公司於 2018/12/05 [解散](https://findbiz.nat.gov.tw/fts/query/QueryCmpyDetail/queryCmpyDetail.do?objectId=SEM2MTgwMzc5Nw==&banNo=61803797)

**Comment by appleboy** [comment]
@a2n 感謝告知
