### ISSUE TITLE
[台中][40K+] 傑富資訊科技有限公司 PHP 網站開發工程師

### ISSUE THREAD

**Issue by Jetfuel00** [golangtw/jobs#32]
## 團隊簡介
＊歡樂的工作氣氛與充滿活力熱血的優質團隊。
 
＊公司穩定成長中，擁有各自可發揮的舞台。
 
我們是遊戲軟體開發公司。 
目前 Jetfuel 正在積極尋找一起工作的技術伙伴，只要您對網站開發相關技術有熱忱與實力，都歡迎您來加入我們！ 
我們主要使用 PHP Laravel 來開發網站。 

## 工作地點
台中市北屯區崇德路二段252號13樓

## 工作內容
1. 規劃設計網站前後台架構及程式撰寫。 
2. API 的開發與介接。 
3. 套版或是寫 API 給前端工程師接。 

## 能力需求
希望您至少具備有以下能力： 
1. 使用過任何一種 PHP Framework 的經驗，或了解 MVC (Model 2) 架構。 
2. 熟悉任何一種 RDBMS (MySQL、MariaDB、PostgreSQL 等等) 的使用。 
3. 熟悉 Javascript、AJAX。 
4. 使用過任何一種版本控制系統。 
5. 基本的 Linux 系統操作。 
6. 不排斥單元測試與 CI。 

## 薪資範圍
40,000-70,000以上，按經歷核薪

## 工時/特休
每日工作時間: 09:00 ~ 18:00；中午休息(12:00~13:00)
週休二日、見紅就放
1.  符合勞基法的休假制度 
2.  療癒身心的年度特休假 

## 福利/推薦項
■ 年終獎金、績效獎金 
■  不定期重要時刻獎金 
■ 順暢的升遷管道
■ 良好的職涯發展環境 
■ 食衣住行全包的特約商店 
■ 不定期員工聚餐 & 康樂活動
■ 定時定點的點心餵食 
■ 每日特選咖啡，無限量供應 
■ 彈性上下班、人性化管理 
■ 不定期多元知能課程 
■ 不定期員工關懷講座 
■ 明亮寬敞的辦公環境  
■ 咖啡機、微波爐、冰箱、飲水機等完善設備
■ 法定保障的勞工保險、全民健保、勞退金提撥 
■ 重視同仁的健康檢查補助 
 

## 聯絡方式
連絡人：錢先生
連絡信箱：hr@jetfuel.com.tw 
連絡電話：04-22474150

**Comment by mikunalpha** [comment]
跟Golang有關? 打算 PHP 轉 Golang 嗎 XD
