### ISSUE TITLE
[台北][80K-120K][卓易科技] 資深軟體工程師 Senior Software Engineer (Dev Force Lead)

### ISSUE THREAD

**Issue by ingted** [golangtw/jobs#36]
## 團隊簡介

從0開始 build team，歡迎推薦你想一起合作的夥伴

## 工作地點

台北101大樓32樓E

## 工作內容

(不是supervisor...是mentor)
Dev Force Lead 角色負責訓練新人，讓新人與你匹敵(?!... 是的，這需要時間與耐心...)
初期只要確保新人在訓練後具有能完成 Core Dev 提供的 solution 即可
中長期則負責帶領 team member 檢視架構，並且協助平台各項開發流程的標準化

## 能力需求

2年以上 golang 實務開發經驗
熟悉 Linux Kernel / networking 尤佳
熟悉 K8S 尤佳

## 加分能力

node.js / Lua / Python scripting

## 薪資範圍

80K-120K / per month

## 工時

40hrs/week

## 特休

比照勞基法，面議
目前正在跟總公司確認(爭取)當中XD

## 福利/推薦項

免費咖啡
上海出差機會!!

## 聯絡方式

anibal.yeh@droi.com
anibal.yeh@gmail.com
葉先生 0982121974
LINE ttcbb
WeChat ttcbby

**Comment by mikunalpha** [comment]
薪資是不是 80K-120K? 少個0

**Comment by ingted** [comment]
updated. thx!!

**Comment by appleboy** [comment]
@ingted 我關掉 #37 了，應該跟這篇重複對吧？

**Comment by DroiPlatform** [comment]
這兩篇內容不同阿....@@

**Comment by appleboy** [comment]
@DroiPlatform 我把這篇的標題改一下，應該是徵求軟體主管，並非是資深工程師了吧

**Comment by DroiPlatform** [comment]
目前是8-10人的小team，分兩個小組，如果今年一切順利，後面會有更多預算，組織結構才會有軟體主管...
這邊指的是supervisor...

**Comment by appleboy** [comment]
@DroiPlatform 沒問題，標題跟內文寫清楚就可以了。
