### ISSUE TITLE
[台北][50K-110K][卓易科技] 資深軟體工程師 Senior Software Engineer (Core Dev / Dev Force)

### ISSUE THREAD

**Issue by ingted** [golangtw/jobs#37]
## 團隊簡介

從0開始 build team，歡迎推薦你想一起合作的夥伴

## 工作地點

台北101大樓32樓E

## 工作內容

與 Core Dev Lead 合作
實作 solution 框架介面 / 定義 solution 資料結構...等
視需求驗證 solution 框架 之 正確性 / 可用性 / 可靠度
將產出交付給 Dev Force 去完成 solution 

## 能力需求

2年以上 golang 實務開發經驗
熟悉 Linux Kernel / networking 尤佳
熟悉 K8S 尤佳

## 加分能力

node.js / Lua / Python scripting

## 薪資範圍

50K-110K/per month

## 工時

40hrs/week

## 特休

比照勞基法，面議
目前正在跟總公司確認(爭取)當中XD

## 福利/推薦項

免費咖啡
上海出差機會!!

## 聯絡方式

anibal.yeh@droi.com
anibal.yeh@gmail.com
葉先生 0982121974
LINE ttcbb
WeChat ttcbby

**Comment by appleboy** [comment]
duplicated of #36

**Comment by DroiPlatform** [comment]
這兩篇不一樣阿...為什麼要關掉呢?@@

**Comment by appleboy** [comment]
標題可能要改一下，避免誤會。一個是徵求 Core Dev Lead

**Comment by DroiPlatform** [comment]
收到
