### ISSUE TITLE
[台北信義區] [天堂遊戲有限公司]誠徵Golang後端資深工程師

### ISSUE THREAD

**Issue by PSZYLim** [golangtw/jobs#42]
http://www.paradise-soft.com/about.html
我們的英文一群由QA，IT，RD組成的團隊，主要的任務是
開發遊戲渠系統，每月處裡千萬訂單的流量
協助公司產品（Web，Mobile Web，APP）測試
建立監控機制，處理CI / CD流程及雲端的管理

我們團隊有用到哪些技術呢?
1. Golang/C#/Python
2. Jenkins/Gitlab/Slack/Redmine/TestLink
3. Selenium/Docker/AWS/GCP/Azure
4. Mysql/Elasticsearch
5. Prometheus/Graylog

工作地點
台北文創大樓（捷運國父紀念館站或市政府站）

工作內容
參與公司後端專案的開發，編寫指定的模組功能 
參與遊戲平台與第三方的串接開發（目前我們每個月處理玩家的遊戲單量都千萬筆以上）
開發公司內部自動化運維平台
docker部屬平台的開發（如果對kubernetes，Swarm有興趣歡迎一起來研究討論）
能力需求
願意學習新知識
了解RESTful API集成與實現
至少有一門編程語言開發經驗（Golang，C＃，Java，Python），我們這邊都是用golang（歡迎對Golang有興趣的來聊聊喔）
對SQL與Mysql有一定程度的了解
熟悉git版控和CI / CD相關經驗
對自動化流程有興趣的
加分能力
1.對碼頭有相關的經驗（目前Prod環境全部的服務都已經docker化在跑了）
2.積極有熱情，樂於分享

薪資範圍
1百萬-2百萬/年（依能力經驗調整）

工時/特休
彈性上下班，09：00-18：00，彈性一小時
午休，12：00-13：00

福利/推薦項
基本該給都不會少給，有吃不完的零食，供午餐，晚餐加班還有下午茶
年終2個月，還有固定調薪，專案獎金等... 
優於法令的特休假等等
公司活動例如：瑜珈，拳擊有氧，漆彈，爬山，解謎，聖誕節交換禮物等....

聯絡方式
lucy_lin@paradise-soft.com
請於信件上註明，於從GitHub的上應徵Golang後端資深工程師-name

**Comment by PSZYLim** [comment]
彈性上下班，09：00~18：00，彈性一小時
午休，12：00~13：00。

**Comment by PSZYLim** [comment]
彈性上下班，09：00-18：00，彈性一小時
午休，12：00-13：00。

**Comment by appleboy** [comment]
@PSZYLim 月薪多少起跳？

**Comment by appleboy** [comment]
@PSZYLim 另外要不要稍微排版一下？文章內容有點亂

**Comment by PSZYLim** [comment]
@appleboy 我修正一下，謝謝您喔！
