### ISSUE TITLE
[徵才] AI-PATTERN 智版信息科技有限公司-徵求後端工程師

### ISSUE THREAD

**Issue by elainechen7366** [golangtw/jobs#43]
## 團隊簡介
智版科技是一間正在萌芽中的公司，我們的目標是致力於打造一個人性化，功能強大的服裝設計線上系統，這是一個全新概念的平台，我們已經計畫了長遠的商業模式，清楚明白每個階段的目標，以及如何融資變現．目前團隊除了有跨足服裝各項產業的專家之外，還有結合服裝與科技業的跨界人員，正因為我們融合了不同產業的背景，更能客觀地審視與解決服裝產業的痛點．很希望能找到共同奮鬥的夥伴，一起跨越每個里程碑，共享努力的成果！

## 工作地點
台北市中山區長安東路二段100號7樓

## 工作內容
1. 開發平台後端架構
2. 有Web/Cloud API網路實務者佳(如AWS , Google API)

## 能力需求
1. 具Java/PHP/Python/Ruby等獨立開發經驗
2. 有RESTful/ WebService/ API開發、串接經驗
3. 至少參與過2項以上的網站開發案
4. 懂MongoDB、SQL，具MySQL相關經驗
5. 兩年以上相關開發經驗
6. 熟悉Git版本控管

## 加分
1. 對金流串接有相關經驗
2. 懂JavaScript/jQuery、CSS/Bootstrap，並知道如何使用 AJAX
3. 過去有接觸過大數據

## 薪資範圍
NTD 50,000 up (依能力經驗再做調整)
另有員工認股制度

## 工時/特休
休假依勞基法規定
彈性工作時間: 8:30AM ~ 7:30PM (自選8hr) 中午休息1hr
每周工作時間: 8*5=40

## 福利/推薦項
每個月有1天的Remote work day可以自由選擇工作地點
鼓勵自主學習，購買相關書籍、課程等可申請補助
如果提出超棒的idea被採用，或者團隊達成階段性目標，將有各種獎勵制度
咖啡茶包小零食想吃就吃，另有不定期下午茶供應

## 聯絡方式
請將
履歷/自傳/作品集
一併寄至 elaineycc114@gmail.com

**Comment by appleboy** [comment]
@s33572 請問這是找 Golang 後端嗎？

**Comment by elainechen7366** [comment]
@appleboy  不好意思我沒仔細看好版名，等等自刪!
