### ISSUE TITLE
[台北] [天堂遊戲有限公司] 誠徵後端工程師

### ISSUE THREAD

**Issue by PSZYLim** [golangtw/jobs#44]
我們是一群由QA、IT、RD組成的團隊，主要的任務是
1. 開發遊戲渠系統，每月處裡千萬訂單的流量
2. 協助公司產品 (Web,Mobile Web,APP)測試
3. 建立監控機制，處理 CI/CD 流程及雲端的管理

我們團隊有用到哪些技術呢?
1. Golang/C#/Python
2. Jenkins/Gitlab/Slack/Redmine/TestLink
3. Selenium/Docker/AWS/GCP/Azure
4. Mysql/Elasticsearch
5. Prometheus/Graylog

## 工作地點
台北文創大樓（捷運國父紀念館站或市政府站）
公司提供舒適環境及福利制度，員工只要專注於自己工作即可

## 工作內容
參與公司後端專案的開發，編寫指定的模組功能 
參與遊戲平台與第三方的串接開發（每個月處理玩家的遊戲單量都千萬筆以上）
開發公司內部自動化運維平台
docker部屬平台的開發

## 能力需求
1. 對 docker 有相關的經驗
2. 瞭解RESTful API集成與實現
3. 至少有一門編程語言開發經驗(Golang, C#, Java, Python等)
4. 對 SQL 與 Mysql 有一定程度的了解
5. 熟悉git版控和CI/CD 相關經驗
至少有3年工作經驗以上

## 加分能力
1.對碼頭有相關的經驗（目前Prod環境全部的服務都已經docker化在跑了）
2.積極有熱情，樂於分享

## 薪資範圍
60K/月以上起跳，最高面議，年終2個月

## 工時/特休
彈性上下班，09：00- 18：00，彈性一小時
午休，12：00- 13：00

## 福利/推薦項
基本該給都不會少給，有吃不完的零食，供午餐，晚餐加班還有下午茶
年終2個月，還有固定調薪，專案獎金等... 
優於法令的特休假等等
公司活動例如：瑜珈，拳擊有氧，漆彈，爬山，解謎，聖誕節交換禮物等....

## 聯絡方式
lucy_lin@paradise-soft.com
請於信件上註明，於從GitHub的上應徵後端工程師-name
請務必附上自傳！

**Comment by appleboy** [comment]
這篇跟 https://github.com/golangtw/jobs/issues/40 哪邊有差異？不同職務嗎？

**Comment by PSZYLim** [comment]
有點像但不同職位，起薪跟要求工作年資較高，還是您建議#40合併呢?

**Comment by appleboy** [comment]
@PSZYLim 建議合併成一個，然後裡面內容可以說明有兩個缺，一個是資深跟一般的差異，然後給的起薪條件不同。我先關掉此 issue，麻煩您修改原先那篇，畢竟那篇已經分享到 FB 了。
