### ISSUE TITLE
[台北/80K] (思華科技誠徵) Golang高級開發工程師

### ISSUE THREAD

**Issue by vivianchiang68** [golangtw/jobs#46]
上班地點: 台北101大樓
## 工作內容
1. 負責後端業務邏輯實現與介面開發 
2. 負責相關模組的軟體設計以及相關文檔編寫 
3. 資深、技術強者薪資面談，不封頂 
## 能力需求
1. 具有良好的團隊合作精神，有較強的開發能力和靈活性。 
2. 開發經驗豐富，熟悉Golang語言，基礎扎實，3年以上Golang開發工作經驗，有完整的項目經驗。 
3. 精通Golang協程，精通Channel和鎖，對高併發、高可用架構系統有正確、深刻的理解，有分散式伺服器開發經驗。 
4. 對RESTful概念有清晰的理解。 
5. 熟悉XML / JSON / Protobuf等至少任意一種網路通信技術和資料交換格式。 
6. 良好的演算法基礎和清晰的程式設計思路。 
7. 熟悉TCP/IP、HTTP等網路通訊協定。 
8. 工作積極主動，態度踏實認真，有較強的職業素養和工作操守。 
9. 對技術有激情，喜歡鑽研，能快速接受和掌控新技術，學習能力和工作責任心強，良好的溝通表達能力和團隊協作能力。 
10. 熟悉Docker者優先。 

## 薪資範圍
月薪 80,000元~150,000元 資深、技術強者薪資面談，不封頂
## 工時/特休
週休二日
## 福利/推薦項
1. 具市場競爭力的薪資 
2. 高額績效獎金制度 
3. 保障年薪13個月 
4. 每年季獎金總額2~6個月(依個人績效考核而定) 
5. MacBook Pro 工作機 
6. 優於勞基法之休假制度 
7. 彈性1小時的上下班制度 
8. 配合政府公告補假，但不補班，2019年等於多了4天的休假 
9. 每月部門Team Building費用補助 
10. 免費辦公室咖啡、飲料及泡麵、零食 
11. 不定期下午茶、部門聚餐 
12. 舒適的員工休息室 
13. 年終尾牙 
14. 公司位於101大樓，明亮、寬敞、舒適的辦公環境

## 聯絡方式
vivian.chiang@silkrode.com.tw
caridee.ding@silkrode.com.tw

**Comment by appleboy** [comment]
https://www.facebook.com/groups/269001993248363/permalink/1164138317068055/
