### ISSUE TITLE
JAVA後端開發工程師_Corp. SCP(台北內湖) 

### ISSUE THREAD

**Issue by MandyYao** [golangtw/jobs#49]
## 團隊簡介
本單位為隸屬於台達企業本部的「軟體共同平台管理部」 
主要負責軟體開發流程的標準化制訂與軟體開發自動化工具導入， 
以及建立元件共享平台以達到元件共用，希望藉此提升軟體開發效能及軟體品質 
## 工作地點
台北市內湖區瑞光路186號(台達電子內湖研發中心)
## 工作內容
負責 JAVA後端開發 
## 能力需求
1. 熟悉HTML5、JavaScript、jQuery、Boostrap、Eclipse等開發工具 
2. 熟悉 JAVA , DAO 任一MVC架構如Spring Frame work 或NodeJS 
3. 基本理解JavaScript 、HTML5 、React 、 jQuery 
4. 了解SQL Server或懂NoSQL技術尤佳 
5. 了解Eclipse plug in 撰寫
## 薪資範圍
年薪保14個月+績效獎金+分紅 (視個人績效表現而定)
## 工時/特休
工時: 週一到週五 8:30-17:30
特休依勞基法規定
## 福利/推薦項
1. 完整教育訓練制度
2. 每年黃金旅遊週假期 + 旅遊補助
3. 備有員工餐廳、咖啡廳、水果攤及三餐伙食補助
## 聯絡方式
歡迎投遞履歷至 mandy.wl.yao@deltaww.com
Mandy Yao

**Comment by appleboy** [comment]
這裡是 golang 版
