### ISSUE TITLE
[台北] [0.6M - 0.8M] 香港商天奕科技 架構師/工程師

### ISSUE THREAD

**Issue by ingted** [golangtw/jobs#57]
公司資訊：
香港商天奕科技台北辦事處，內湖，聯發科旁邊。
@mikunalpha @kettan 是我們歷任的架構師/Team Lead
0227996606 #111 Carrie 

工作資訊：
1. 職稱：架構師/工程師
2. package range：1.2M~ 1.4M / 0.6M ~0.8M
3. 年資經驗：golang 3yr+/C or C++ or C# or JAVA 1 yr+ or golang 3month+
4. 薪資結構：月績效獎金/年終一個月/滿三個月獎金/過試用調薪
5. 福利：工作合拍，上手順利後可 remote。不加班。晚上有 op 的話可以前天休假或次日休假。滿三個月10天特休。離職勞健保不會斷(e.g. 週五最後一天，但是薪水勞健保會算到週日或者假期結束)。

你要帶著一起衝鋒的夥伴資訊：
1. 沒有 C style 的 C 轉 GO 手遊高手
2. 一個行旅生涯的年輕人
3. 喜歡玩狼人殺的 DBA/DBD 一名
3. 一個弄 ML 的新手，天堂二的老手

開發中的東西：
1. 用很多手機監控 CDN 服務的 APM 
2. 給開發者 SDK 方便存取後端微服務的 BaaS (backend as service) 平台

意者歡迎私訊：
wechat：ttcbby
telegram：@ttcbby

面試可配合您的時間與地點(如果為雙北...)，外縣市的話，可以雙方配合選一個中間的地點。可以有首年的 relocation 津貼。

**Comment by mikunalpha** [comment]
聽說解散了

**Comment by appleboy** [comment]
@mikunalpha 大大是真的嗎？

**Comment by ShawnOY** [comment]
整個撤掉了無誤
