### ISSUE TITLE
[台北] [77k以上] [PolicyPal] Full-Stack Engineer

### ISSUE THREAD

**Issue by YengTsan** [golangtw/jobs#6]
## 團隊簡介
PolicyPal helps consumers to manage, optimise insurance policies through the OCR technology and AI chatbot, offering personalised recommendations using social media and existing policies data. We are the first fintech and currently only startup to enter MAS Fintech Regulatory Sandbox in Singapore. We are funded by 500 startups and working with global insurance companies disrupting this space.

【Simplicity】 
We believe insurance does not have to be complicated – PolicyPal is here to innovate and keep it simple.

【Transparent】 
We uphold the value of transparency – in respect to our insurance solutions and our daily work.

【Driven】 
We are driven to make a difference to the insurance industry by implementing positive solutions to benefit both consumers and insurers.

【Excellence】 
We want to offer the best insurance experience - that is why we place huge emphasis on listening to your feedback.

## 工作地點
可選 台北 或 至新加坡工作

## 工作內容
We are looking for talented and bold engineers who love to code, get their hands dirty with raw data and derive meaningful and actionable insights. To keep our pace up, we need passionate Developers who challenge the status quo on a daily basis and are driven to go the extra mile. As an engineer at PolicyPal you have the platform to continue to grow, evolve and learn. The challenge is to adapt ideas quickly and offer our customers a solution that provide value on every dimension. Here we don't want to be good at what we do,we aim to be the extraordinary at it!

## 能力需求
•	Full stack generalist with deep knowledge in back-end software 
•	Comfortable working on everything from Golang, React native, mySQL, AWS, and third-party API integrations 
•	You've built scalable software on your own from the ground up 
•	Experience designing and deploying database systems 
•	Get It Done mentality. From setting up AWS servers to debugging live with clients, take ownership of issues and move ‘em. 
•	Ability to keep calm in start-up uncertainty 
•	Works hard but loves to share a laugh and wants to build a fun work culture

## 加分能力
•	Fintech experience 
•	Start-up experience 
•	Knowledge of data encryption and security 
•	Web and mobile app development 
•	Project management experience

## 薪資範圍
NT$77,000 - NT$121,000(月薪)

## 工時/特休
9:00-18:00                                                                      
中間休息一小時                                                                  

## 招募近況
★創辦人將於7/3 ~ 7/7來台進行面試 請儘早投遞★ 

## 聯絡方式
https://www.yourator.co/companies/PolicyPal/jobs/2572

**Comment by ReinhardtLin** [comment]
就我所知，這個工作應該不是在台北，而是在新加坡

**Comment by YengTsan** [comment]
創辦人說可以自由選擇台北與新加坡唷

**Comment by appleboy** [comment]
新職缺已經換成: https://github.com/golangtw/jobs/issues/7

**Comment by appleboy** [comment]
詳細原因可以直接看 https://github.com/golangtw/jobs/issues/7#issuecomment-310888529
