### ISSUE TITLE
[桃園] [50K 起跳] 雲中雲徵 GoLang 工程師數名

### ISSUE THREAD

**Issue by coco0223** [golangtw/jobs#64]
## 團隊簡介
雲中雲有限公司, 統一編號：82814237 , 登記機關：桃園市政府, 主要業務是開發線上遊戲賣給海外客戶去經營
## 工作地點
桃園市中壢區高鐵站前西路一段268號3樓之8
## 工作內容
實作RESTAPI, WebSocket, 以及數據分析, 存取 MySQL, Radis, 具分佈式系統經驗優先.
## 能力需求
請參考工作內容
## 加分能力
如上
## 薪資範圍
5萬~15萬
## 工時/特休
周休二日, 每半年5天特休.
## 聯絡方式
edem@cinc.tw

**Comment by pipiBRH** [comment]
這是你們公司嗎?
https://www.ptt.cc/bbs/Tech_Job/M.1566005715.A.F68.html

**Comment by wowissu** [comment]
https://disp.cc/b/163-bCpH

**Comment by kkc** [comment]
這家還在嗎ＱＱ

**Comment by mikunalpha** [comment]
> 這家還在嗎ＱＱ

不在了吧

**Comment by appleboy** [comment]
先關閉
