### ISSUE TITLE
[台北] [70K ~ 150K] 百阜科技尋找 GoLang 新團隊夥伴

### ISSUE THREAD

**Issue by emmachangsa** [golangtw/jobs#65]
## 百阜團隊 
百阜重視積極&團隊合作
我們關心每個夥伴，我們致力提倡快樂工作、享受生活。 
我們創造開朗自由的工作環境及風氣給予每個工作夥伴。

## 工作地點
台北市內湖區

## 工作內容
1.負責 Golang 相關專案、功能開發、迭代計畫實踐、優化系統項目。 
2.負責軟體之分析、設計以及程式撰寫。 
3.規劃執行軟體架構及模組之設計，並控管軟體設計進度。 
4.調研軟體新技術與新工具。 

## 能力需求
1、掌握電腦科學基礎知識，包括演算法、資料結構、作業系統、物件導向程式設計等 
2、2年以上golang服務端研發經驗，本科及以上學歷； 
3、熟悉 Linux 平臺下的 Golang 程式設計，掌握一種及以上go web框架； 
4、熟悉Golang協程，熟悉channel和鎖，對高併發、高可用架構系統有正確、深刻的理解； 

## 加分能力
5、熟悉常用的互聯網技術，包括但不限於MySQL、Redis、RPC、MQ、緩存技術、微服務架構； 
6、能快速接收和掌握新技術，工作自主驅動，具備良好的問題定位分析能力； 
7、具備團隊協作能力，富有挑戰精神和強烈的進取心。 
8、較強的邏輯思維能力、分析問題的能力，善於並表達自己的想法 

## 薪資範圍
年薪100萬~200萬 (技術核薪)

## 工時/特休
彈性上下班

## 福利/推薦項
符合法令要求是基本的
優於法令的族繁不及備載
同仁覺得特別的：
每季電影票發放
公司各大小活動

詳細歡迎來了解

## 聯絡方式
HR Emma
​emma.chang@baifu-tech.net

**Comment by appleboy** [comment]
@emmachangsa 可否提供月薪範圍資訊呢？

**Comment by emmachangsa** [comment]
Hi Bo-yi,

感謝您的詢問，
月薪約落在70k~150k左右，依技術面議核薪。

Emma.



從我的 iPhone 傳送

**Comment by appleboy** [comment]
@emmachangsa 感謝提供資訊，我補上 `70K以上` 的 label

**Comment by kunyaoxu** [comment]
請問貴公司後端目前有意願收資歷相對淺的工程師嗎?

**Comment by appleboy** [comment]
@kunyaoxu 回覆的同時，也可以把履歷寄給對方。

**Comment by emmachangsa** [comment]
@kunyaoxu 不好意思，我這邊好像沒有收到您的信件，所以沒有即時回覆您。
如果您還有興趣進一步了解，是否方便請您再Mail一次呢？感謝。
