### ISSUE TITLE
[台北] [45K以上] 飛騰資訊後端開發工程師

### ISSUE THREAD

**Issue by abelliu1028** [golangtw/jobs#77]
☆飛騰資訊科技有限公司☆
【 擴大徵才 】
Back-End Engineer 後端開發工程師

【 工作內容 】

設計大型、具備容錯能力的雲端服務基礎建設
分析及增進各個子系統的效能、延展性、穩定性
快速的系統迭代和不斷擴大的功能規模
我們在CI/CD的環境下作業，Git、Drone、Dorker、k8s、Helm、Cucumber、grpc...等等的都會圍繞在你身邊

【 工作技能 】

優秀的分析和程式能力
(資深需具備) 僅需要基本引導即可作業
一年以上 (資深需具備三年以上) 軟體開發經驗
(資深需具備) 系統設計的工作經驗
具備系統架構、資料庫、網路相關的知識
曾經有併發、多執行緒、伺服器架構及分散式系統的工作經驗
UNIX/Linux 作業系統、系統管理員相關的知識
我們使用Go 程式語言，也歡迎後端其他語言想轉Go 的人才加入我們
【 加分條件 】

使用過 Agile 工具做專案控管
熟悉mac, linux 環境
mysql, redis,nsq操作
sql script
swagger
6.有Web API部署經驗
【 福利 】
-彈性工時
-免費提供咖啡、氣泡水、飲料、零食與不定期下午茶
-年終獎金
-績效與專案獎金
-節慶禮金與禮品
-生日禮金
-久任與推薦獎金

【 薪資範圍 】
月薪 $45,000 ~ $80,000（依照能力核薪）

【 工作地點 】
台北市信義區（捷運市政府站）

【 聯絡方式 】
LINE:abelliu1028

**Comment by appleboy** [comment]
下次不要建立新的 issue，直接修改舊的就可以了。
