### ISSUE TITLE
[台北/信義區][80K~150K+] 思華科技誠徵 Golang 資深開發工程師

### ISSUE THREAD

**Issue by mikunalpha** [golangtw/jobs#80]
## 團隊簡介
思華科技於2018年8月成立，位於台北101大樓13樓，是一家提供電子交易平台的方案解決者，並以AI數據來分析用戶體驗為我們的客戶提供獨特的B2B客製化解決方案。現行團隊人數已破百人，也陸續擴大徵才中! 

## 工作地點
台北 101

## 工作內容
1. 負責後端業務邏輯實現與介面開發
2. 負責相關模組的軟體設計以及相關文檔編寫

## 能力需求
1. 具有良好的團隊合作精神，有較強的開發能力和靈活性。
2. 開發經驗豐富，熟悉Golang語言，基礎扎實，3年以上Golang開發工作經驗，有完整的項目經驗。
3. 精通Golang協程，精通Channel和鎖，對高併發、高可用架構系統有正確、深刻的理解，有分散式伺服器開發經驗。
4. 對RESTful概念有清晰的理解。
5. 熟悉XML / JSON / Protobuf等至少任意一種網路通信技術和資料交換格式。
6. 良好的演算法基礎和清晰的程式設計思路。
7. 熟悉TCP/IP、HTTP等網路通訊協定。
8. 工作積極主動，態度踏實認真，有較強的職業素養和工作操守。
9. 對技術有激情，喜歡鑽研，能快速接受和掌控新技術，學習能力和工作責任心強，良好的溝通表達能力和團隊協作能力。
10. 熟悉Docker者優先。
11. 因應目前的專案需求，需熟悉C++語言者

## 薪資範圍
NT$ 80,000 – 150,000 (月薪)

## 福利/推薦項
1. 高額績效獎金制度
2. 保障年薪13個月
3. 每年季獎金總額2~6個月(依個人績效考核而定)
4. MacBook Pro 工作機
5. 優於勞基法之休假制度
6. 彈性1小時的上下班制度
7. 配合政府公告補假，但不補班，2019年等於多了4天的休假
8. 每月部門Team Building費用補助
9. 免費辦公室咖啡、飲料及泡麵、零食、牛奶
10. 不定期下午茶、部門聚餐
11. 舒適的員工休息室
12. 年終尾牙

## 聯絡方式
歡迎直接聯繫我：HR Caridee  caridee.ding@silkrode.com.tw
Cakeresume投履歷：https://www.cakeresume.com/cr/104-jobbank-custjob-index-php-r-cust-j-444e466f383a426b34363e673c423a1d02d2d2d71444a4e2644j52-400f94/golang-development-engineer

**Comment by appleboy** [comment]
已加上標籤
