### ISSUE TITLE
[台北/新竹] [45K以上] 優必闊科技後端開發工程師數名

### ISSUE THREAD

**Issue by UbiikTP** [golangtw/jobs#82]
## 團隊簡介
優必闊科技(Ubiik)為台灣工業物聯網解決方案商，成立於2016年，總部位於台灣，分別於日本、美國及印度設有分公司或服務據點。

優必闊科技是全台灣最大智慧電表布建專案的主要供應商之一。該計畫由台灣電力公司主導，規劃在2024年前完成超過300萬個電表的AMI系統部署，預計在未來10-15年內超過1200萬個電表完成安裝。優必闊以通過市場驗證的智慧電表方案為基礎，積極將能源管理及控制方案導入微電網及分散式能源應用領域。

## 工作地點
台北車站、新竹高鐵站附近

## 團隊目標
將微服務、混合雲與數據分析應用在公共事業領域上，推動產業資訊架構革新

## 工作內容
負責後端邏輯實現與介面開發
資料庫設計與高可用性實踐
負責相關軟體模組測試設計

## 能力需求
具有良好的溝通能力，不會害怕講英文
經驗較淺者，具有基本演算法開發能力，並至少熟悉或使用過一種後端語言
開發經驗豐富者，需熟悉Golang語言，且具有完整的專案經驗

## 加分能力
精通Goroutine，對高可用性、災難復原與附載平衡等系統有正確理解
具有Stream server相關使用經驗
NoSQL與SQL高可用性與災難復原架設經驗
理解至少一種資料格式SOAP / XML / JSON / Protobuf等
具有gRPC或Websocket使用經驗
良好的演算法基礎和清晰的程式設計
熟悉TCP/IP、HTTP等網路通訊協定
管理並執行過敏捷式專案，並能與同事溝通協做
具有獨立解決問題的能力，態度認真

## 薪資範圍
NT$ 45,000 – 120,000 (月薪)

## 工時/特休
優於勞基法的特休

## 福利/推薦項
保障薪資14個月
績效獎金與分紅制度

如果你喜歡幽默對話  國際團隊  效率工作  這裡就是你所尋找的地方

## 聯絡方式
請直接將履歷聯繫HR Caridee tinna.chang(at)ubiik.com

**Comment by appleboy** [comment]
@UbiikTP 感謝發文，已經加上 label 標籤

**Comment by appleboy** [comment]
公司 HR 說要關閉，會重新發一篇
