### ISSUE TITLE
[台北] [年薪80萬以上] 前端/全端工程師

### ISSUE THREAD

**Issue by ghost** [golangtw/jobs#86]
// 以下是建議填寫項目，可自由增刪排序~ // 也建議標註團隊目前技術框架 // ^ 上面的看完就可以刪了~

## 團隊簡介
獲獎無數的引達取有限公司是發跡於英國的線上遊戲開發商。在數位娛樂（iGaming/ eGaming ）產業據重要地位，超過兩百萬的玩家活躍於旗下多個知名遊戲品牌。製作、發行與營運的遊戲相容於 iOS, Android 與 PC 系統，能支援近 99% 的硬體裝置。目前全球有超過 400 位員工分據赫索溫（Halesowen, UK）、布加勒斯特（Bucharest, RO）、吉隆坡（Kuala Lumpur, MY）、東京（Tokoy, JP）與台北（Taipei, TW）。

主要商品 / 服務項目
英商引達取有限公司提供數位娛樂（iGaming/ eGaming ）的一站式解決方案，更是英國 App Store 與 Google Play 遊戲排行榜的常勝軍。在亞洲地區尤其專注於遊戲開發，以每月 4-6 款的速度產出多語系的各類型電子遊戲，並透過 SF 電子（亦稱老虎機樂園 Slot Factory ）品牌拓展全球商機、尋求 B2B 合作機會。請詳閱 slotfactory.com 以了解更多產品訊息。
## 工作地點
交通位置便利-北市大同區承德路一段(京站附近/中山站五號出口步行5分鐘內)
## 工作內容
我們在尋找一名前端/全端工程師，專門負責資料處理，中介服務及用戶管理。主要處理客戶端與伺服器端的程式邏輯，資料定義與管理。
工作內容：
- 擔任技術跟架構的開發角色
- 需與產品經理，介面設計還有國外其他開發工程師一起合作改善功能設計
- 提供專業技術來配合商業邏輯開發
- 開發並整合客戶的API

## 能力需求
- 2年以上React能力
-了解前端技術包含JavaScript， HTML 與 CSS.
- 有實作REST API 經驗
- 具有Linux與Bash指令經驗跟知識 (edited)
## 加分能力
- 熟悉任一PHP framework，Laravel 為佳
- 熟悉SQL/NoSQL資料庫（譬如MYSQL and Cassandra）
## 薪資範圍
年薪 800,000元 ~ 1,300,000元

## 工時/特休
彈性工時(上班-09:00-11:00/下班-18:00-20:00)
特休-18天
## 福利/推薦項
具競爭力的 18 天年假
具競爭力的薪資制度
順暢的升遷管道
不定期員工教育訓練
免費下午茶、滿滿零食
明亮寬敞的辦公環境
咖啡機、微波爐、冰箱、飲水機等
彈性上下班時間
員工健康檢查
10.員工團保
11.當月壽星蛋糕
◆ 獎金
1.三節禮金
2.推薦人才獎金

◆ 休假

週休二日
特休/年假
婚假、喪假
陪產假、育嬰假
女性同仁生理假
生日假
◆ 活動

每季公司聚餐
年終尾牙
不定期海外參展
不定期康樂活動
## 聯絡方式
職務聯絡人 | tiffany lin
職務聯絡人信箱 | tiffany.lin@slotfactory.com

**Comment by appleboy** [comment]
是不是發錯地方？這是 Golang Job 版
