### ISSUE TITLE
[台北][80K~200K] 華奧科技誠徵 資深Go工程師[遊戲產品部]

### ISSUE THREAD

**Issue by tedmax100** [golangtw/jobs#88]
## 團隊簡介
華奧科技有限公司（以下簡稱華奧科技）新創立於2020年，由一群曾在知名軟體、網路公司的核心人才和技術菁英帶著對夢想的追求組成，集軟體研發及產業整合於一體的平臺型公司。

作為一間深具實力的新創公司，我們相信『尚未成功』的潛能，遠比『成功』更值得嘉許。
擁有『成長型思維』的人才，都是最適合我們的夥伴。

團隊和諧與付出，是我們最為看重，透過實質福利回饋；只要願意，絕對不吝嗇與團隊分享戰果。

## 工作地點
台北市南港區經貿二路197號

## 產品參考
B2B體育產品 相關開發
此產品純B2B, 無會員與金流業務

## 工作內容
1. 體育產品的前後台與服務開發
2. 與英國團隊協同開發
3. API、DB規格文件設計與撰寫
4. 單元測試
5. CI腳本

## 能力需求
1. 5年以上的開發經驗，精通一門或多門開發語言 (Go, Java, C++，Php，Python，C#等)。
2. 熟悉Golang語言，基礎扎實，1年以上Golang開發工作經驗。
3. 熟悉Golang協程，熟悉Channel和鎖，熟悉微服務架構。
4. 熟悉Redis和MySQL數據庫。
5. 熟悉JSON / Protobuf等種網路通信技術和資料交換格式。
6. 良好的演算法基礎和清晰的程式設計思路。
7. 熟悉TCP/IP、HTTP等網路通訊協定，熟悉websocket。
8. 熟悉Docker，熟悉 git 版本管理。

## 加分能力
1. 有體育或彩票產品經驗者優先
2. Elasticsearch
3. MySQL叢集管理

## 薪資範圍
NT$ 80,000 – 200,000 (月薪)
有實力者可超過此範圍

## 工時/特休
日班，9:00---18:00

## 福利/推薦項
1、彈性上下班時間：8:30 上班，即可 17:30 下班
2、有給職員工皆參與勞工保險、全民健康保險。
3、提供員工教育訓練。
4、婚、喪、生育、傷病急難救助等補助金。
5、每月員工聚餐、聚會。每三個月一次員工電影欣賞會
6、優於勞基法的特休：以曆年制計假，到職第一年起即享 10 天(依到職日採比例計算)
第二年起10天，第三年享14 天
(例: 2018/7/1 到職，當年度按比例享有 4 天特休，2019/1/1 起即享 10 天特休)
特休假未休完者，將轉換薪資並於次月發放。
7、每年 18 天的全薪病假
8、節慶連假前一天，全體員工提前一小時下班，避開人潮、車潮
9、三節獎金

## 聯絡方式
聯絡人: Caden
Email: caden@hwaotech.com
可以直接Telegram私聊
TG : barango666

**Comment by appleboy** [comment]
請問這篇可以關掉？https://github.com/golangtw/jobs/issues/83
