### ISSUE TITLE
[台北] [84K以上] COBINHOOD 柯賓漢數位金融科技 Backend Developer

### ISSUE THREAD

**Issue by richardcwyo** [golangtw/jobs#9]
## 團隊簡介
Cobinhood is a place for dreamers and doers.
Cobinhood has vision to become the largest and most successful cryptocurrency exchange in the world.

You’ll work on the bleeding edge of blockchain technology, including Bitcoin, Ethereum and other cryptocurrencies, and play an important role in helping shape the future of how the world sees and uses money.

## 工作地點
Xinyi District, Taipei City

## 工作內容
Develop high quality, high concurrency, high availability, high scalability distributed micro services and API backend.

Cobinhood is a place for dreamers and doers.
Cobinhood has vision to become the largest and most successful cryptocurrency exchange in the world.

You’ll work on the bleeding edge of blockchain technology, including Bitcoin, Ethereum and other cryptocurrencies, and play an important role in helping shape the future of how the world sees and uses money.

## 能力需求
+ 3+ years backend working experience
+ 2+ years of experience developing production-level application
+ Solid knowledge in network protocols (TCP/IP/HTTP/HTTPS) 
+ Proficiency in Python / Golang
+ Familiar with designing RESTful APIs
+ Rich experience with databases and SQL/NoSQL
+ Knowledge and experience in Linux
+ Knowledge and experience in AWS/GCP
+ Experience with Kubernetes, Docker, DevOps and CI/CD procedures
+ Experience with Bitcoin / Ethereum / Smart Contracts is a plus
+ Passionate on new technologies
+ Strong initiative and enthusiasm, self-motivated

## 薪資範圍
Annual NTD84,000-NTD150,000 x 14

## 工時/特休
一到職即給7天特休

## 福利/推薦項
+ 公司近捷運象山, 101站
+ 彈性上下班，再也不用擠電梯擠車位了
+ 不打卡，不簽到
+ 休假制度優於勞基法：報到當日起即給與7天特休
+ 員工配股/員工認股
+ 每月點心櫃補到滿，想吃什麼自己點
+ 每位員工皆配備apple筆電
+ 彈性午休時間
+ 每週例行歡樂午餐時光，各種知名餐廳與美味餐點等著你
+ 豐厚獎金，肯拚就有收穫
+ 主管級員工椅及休息區，午睡時光讓你精力充沛

## 聯絡方式

cv/resume sent to careers@cobinhood.com

**Comment by Hunsin** [comment]
薪資已是Annual，x14的意思是？

**Comment by p3y-deg** [comment]
一年固定領 14 個月。

Tsai, Hsiao-Chieh <notifications@github.com>於 2017年8月15日 週二，17:43寫道：

**Comment by richardcwyo** [comment]
謝謝  @p3y-deg 幫忙回答！是的一年固定14個月，薪資範圍是指月薪

**Comment by appleboy** [comment]
我幫忙更新標題了 `[台北] [84K以上] Cobinhood 柯賓漢數位金融科技 Backend Developer`

**Comment by bogi-lucas** [comment]
我去  这不是COB吗 我还参加了ico

**Comment by appleboy** [comment]
公司解散 https://www.blocktempo.com/cobinhood-closure-of-business/
