### ISSUE TITLE
【工作氛圍優，福利佳】Java工程師／Java資深工程師

### ISSUE THREAD

**Issue by icchance** [golangtw/jobs#91]
// 以下是建議填寫項目，可自由增刪排序~ // 也建議標註團隊目前技術框架 // ^ 上面的看完就可以刪了~

## 工作地點
台北
## 工作內容 
1.協助架構及開發公司營運所需服務
2.軟體程式撰寫與維護
3.規劃程式架構及系統整合
4.系統分析、程式設計及文件撰寫
5.熟悉 Java web application 開發技術
6.孰悉物件導向與 MVC 架構觀念
7.熟 Spring Framework、Hibernate、MySQL、Oracle、Maven
8.熟悉異質平台介接 (XML/JSON/SOAP 等規格)
9.熟 Linux
10.主管交辦事項
## 聯絡方式
chance_hr@icchance.com

**Comment by gtbcoding** [comment]
好像跟Golang沒有任何關係...
