### ISSUE TITLE
[台北/中山][年薪90-120萬]【旋轉拍賣 Carousell】Software Engineer, Backend 後端工程師

### ISSUE THREAD

**Issue by Carousellhr** [golangtw/jobs#94]
## 團隊簡介
Carousell旋轉拍賣是讓網路買賣跟拍照聊天一樣簡單的手機app。2012年8月在新加坡推出，目前已取得新加坡行動拍賣平台的龍頭地位，並拓展至台灣、香港、馬來西亞、菲律賓、印尼、越南、緬甸，現有超過2億5千萬件刊登商品，是全球最大且成長最快速的社群拍賣平台之一。

**核心價值**
Mission First : 旋轉拍賣的使命是「To inspire every person in the world to start selling」。為了達成這個的使命，不要害怕提出自己的意見，要勇於發聲。而當面對困難的決定時，也必須回頭看看我們的使命，是不是走在正確的方向上。

Solve Problem : Carousell 旋轉拍賣的初衷就是為了解決購買產生的「浪費」，這些陳放在家中的二手用品，可能正是別人需要的東西．

Relentlessly Resourceful：新創的限制其實非常多，資源的限制、人力的限制都時常發生，團隊成員要有竭盡所能完成任務的創意及決心。

Care Deeply：團隊成員不只做好自己的工作，也會關心同事，彼此交流，因為我們比你更在乎你的成長。除此之外，我們也很重視用戶的感受，將用戶視為「個人」，而非只是「流量」。

Stay Humble：就算做得再好再努力，我們永遠要認為自己只達到99分。永遠保持反省的心，不論在產品上、在技術上、在組織上，持續為那1分的進步空間不懈努力。

## 工作地點
台北中山

## 工作內容
・Design and build scalable APIs for the Carousell marketplace platform.
・Work with the Android, iOS, web, product and design teams to build innovative, robust, and easy-to-use features for our users.
・Write clean, testable code with unit tests.
・Work with the infrastructure team on deploying, scaling and performance optimization.
・Participate in code reviews to maintain a high-quality code culture.

## 能力需求
・User obsession and empathy.
・Drive and resourcefulness to persevere and overcome obstacles achieving challenging goals.
・Focus on impact and results. You work on the right things and get them done.
・High integrity and ability to positively collaborate with others
・Experience in either Go, Python, Django/Flask, RESTful APIs
・Ability to write clean, maintainable and performant code making use of appropriate design principles and patterns.
・Experience using RDBMS such as PostgreSQL and technologies such as Redis, Cassandra, Kafka, Lucene / Elasticsearch / Solr.
・Strong experience in optimizing the performance of backend systems and scaling infrastructure components.
・Experience in building large, scalable distributed systems with good understanding of microservices architecture and ・associated principles.
・Experience with TDD/BDD and agile methodologies
・Degree in Computer Science, Software Engineering or other equivalent degrees/experience
・3+ years experience in software development

## 加分能力
・Experience with online classifieds marketplace.
・Knowledge of managing data consistency in distributed systems.
・Experience working with asynchronous systems.

## 薪資範圍
年薪90~120萬(月薪7.5至10萬)，視工作經驗與能力而定

## 工時/特休
每日八小時彈性工時

## 福利/推薦項

・配備Macbook Air/Pro
・輕工業風開放辦公空間
・免費零食和健康水果，保證你隨時都有東西可以吃
・每月兩次Together Thursday提供免費午餐，同時會由新加坡總部進行全球同步連線，分享最新動態
・國際化工作環境，可以向不同國家、不同團隊同事線上學習交流
・不定期員工聚餐、Team building活動以及到新加坡總部交流機會
・享有勞健保、團保、健檢和個人訓練補助
・優於勞基法的年假制度

## 聯絡方式
請至旋轉拍賣官方招募網站投遞履歷
https://careers.carousell.com/job-posting/?gh_jid=2316973

**Comment by appleboy** [comment]
請問有月薪資訊嗎？

**Comment by Carousellhr** [comment]
@appleboy 你好～已更新月薪資訊，謝謝!

**Comment by appleboy** [comment]
@Carousellhr 非常感謝，已經補上 Label 了。
